### ISSUE TITLE
Error in hand_bbox_detector 

### ISSUE THREAD

**Issue by lan786** [facebookresearch/frankmocap#10]
Hi, thanks for this wonderful repo. I'm facing problem when I run handmocap or frankmocap. Bodymocap is working fine. 

Problem:
Getting problem in [hand_bbox_detector line 30](https://github.com/facebookresearch/frankmocap/blob/fa213cee112107214251f9ac72f93430aeb60e32/handmocap/hand_bbox_detector.py#L30) `No module named 'model'`
From where this module is importing? Detectron or hand_object_detector? 
Is there anything missing from myside? 

Note: hand-object_detector compiled successfully and it is working if I test hand_object_detector using any demo image.

**Comment by lan786** [comment]
Solved my problem, there was missing something in code.

**Comment by abhin7993** [comment]
HI @lan786 I am facing the same issue.Could you please let me know, how you solved it?

**Comment by lan786** [comment]
@abhin7993 The only problem is to mention right path, nothing else. just provide this path `detectors.hand_object_detector.lib` if you are following authors instructions otherwise check your files path.
