### ISSUE TITLE
AssertionError: Failed in opening video: ./sample_data/han_short.mp4

### ISSUE THREAD

**Issue by usernamex1x23** [facebookresearch/frankmocap#100]
error when trying
python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output --save_pred_pkl

(frankmocap) D:\video\2\1>python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output --save_pred_pkl
Loading Body Pose Estimator
use_smplx False
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "D:\video\2\1\demo\demo_bodymocap.py", line 178, in
main()
File "D:\video\2\1\demo\demo_bodymocap.py", line 174, in main
run_body_mocap(args, body_bbox_detector, body_mocap, visualizer)
File "D:\video\2\1\demo\demo_bodymocap.py", line 27, in run_body_mocap
input_type, input_data = demo_utils.setup_input(args)
File "D:\video\2\1\mocap_utils\demo_utils.py", line 105, in setup_input
assert cap.isOpened(), f"Failed in opening video: {args.input_path}"
AssertionError: Failed in opening video: ./sample_data/han_short.mp4

**Comment by penincillin** [comment]
@usernamex1x23 
It seems that you haven't downloaded the demo data successfully. Would you mind try to solely run this [demo data downloading script](https://github.com/facebookresearch/frankmocap/blob/master/scripts/download_sample_data.sh)

**Comment by usernamex1x23** [comment]
where do i copy past this code

**Comment by usernamex1x23** [comment]
(frankmocap) D:\video\2\1>python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Loading Body Pose Estimator
use_smplx False
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\video\2\1\demo\demo_bodymocap.py", line 178, in <module>
    main()
  File "D:\video\2\1\demo\demo_bodymocap.py", line 174, in main
    run_body_mocap(args, body_bbox_detector, body_mocap, visualizer)
  File "D:\video\2\1\demo\demo_bodymocap.py", line 27, in run_body_mocap
    input_type, input_data = demo_utils.setup_input(args)
  File "D:\video\2\1\mocap_utils\demo_utils.py", line 105, in setup_input
    assert cap.isOpened(), f"Failed in opening video: {args.input_path}"
AssertionError: Failed in opening video: ./sample_data/han_short.mp4

(frankmocap) D:\video\2\1>python -m demo.demo_handmocap --input_path ./sample_data/han_hand_short.mp4 --out_dir ./mocap_output
Traceback (most recent call last):
  File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\video\2\1\demo\demo_handmocap.py", line 16, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "D:\video\2\1\handmocap\hand_bbox_detector.py", line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'

(frankmocap) D:\video\2\1>python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Traceback (most recent call last):
  File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\video\2\1\demo\demo_frankmocap.py", line 24, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "D:\video\2\1\handmocap\hand_bbox_detector.py", line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'

**Comment by penincillin** [comment]
Please make sure you have installed detectron-2 and hand detector successfully.

**Comment by usernamex1x23** [comment]
(frankmocap) D:\video\2\1>python -m pip install detectron2 -f \
Looking in links: \
Requirement already satisfied: detectron2 in d:\newfolder\envs\frankmocap\lib\site-packages (0.3)
Requirement already satisfied: pydot in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (1.4.2)
Requirement already satisfied: fvcore>=0.1.2 in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (0.1.5.post20210415)
Requirement already satisfied: tabulate in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (0.8.9)
Requirement already satisfied: yacs>=0.1.6 in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (0.1.8)
Requirement already satisfied: tqdm>4.29.0 in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (4.60.0)
Requirement already satisfied: future in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (0.18.2)
Requirement already satisfied: tensorboard in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (2.4.1)
Requirement already satisfied: cloudpickle in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (1.6.0)
Requirement already satisfied: matplotlib in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (3.4.1)
Requirement already satisfied: Pillow>=7.1 in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (8.2.0)
Requirement already satisfied: termcolor>=1.1 in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (1.1.0)
Requirement already satisfied: pycocotools>=2.0.2 in d:\newfolder\envs\frankmocap\lib\site-packages (from detectron2) (2.0.2)
Requirement already satisfied: pyyaml>=5.1 in d:\newfolder\envs\frankmocap\lib\site-packages (from fvcore>=0.1.2->detectron2) (5.4.1)
Requirement already satisfied: numpy in d:\newfolder\envs\frankmocap\lib\site-packages (from fvcore>=0.1.2->detectron2) (1.20.2)
Requirement already satisfied: iopath>=0.1.7 in d:\newfolder\envs\frankmocap\lib\site-packages (from fvcore>=0.1.2->detectron2) (0.1.8)
Requirement already satisfied: portalocker in d:\newfolder\envs\frankmocap\lib\site-packages (from iopath>=0.1.7->fvcore>=0.1.2->detectron2) (2.3.0)
Requirement already satisfied: cython>=0.27.3 in d:\newfolder\envs\frankmocap\lib\site-packages (from pycocotools>=2.0.2->detectron2) (0.29.23)
Requirement already satisfied: setuptools>=18.0 in d:\newfolder\envs\frankmocap\lib\site-packages (from pycocotools>=2.0.2->detectron2) (52.0.0.post20210125)
Requirement already satisfied: pyparsing>=2.2.1 in d:\newfolder\envs\frankmocap\lib\site-packages (from matplotlib->detectron2) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in d:\newfolder\envs\frankmocap\lib\site-packages (from matplotlib->detectron2) (2.8.1)
Requirement already satisfied: cycler>=0.10 in d:\newfolder\envs\frankmocap\lib\site-packages (from matplotlib->detectron2) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\newfolder\envs\frankmocap\lib\site-packages (from matplotlib->detectron2) (1.3.1)
Requirement already satisfied: six in d:\newfolder\envs\frankmocap\lib\site-packages (from cycler>=0.10->matplotlib->detectron2) (1.15.0)
Requirement already satisfied: pywin32!=226 in d:\newfolder\envs\frankmocap\lib\site-packages (from portalocker->iopath>=0.1.7->fvcore>=0.1.2->detectron2) (300)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (1.8.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (0.4.4)
Requirement already satisfied: google-auth<2,>=1.6.3 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (1.29.0)
Requirement already satisfied: protobuf>=3.6.0 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (3.15.8)
Requirement already satisfied: grpcio>=1.24.3 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (1.37.0)
Requirement already satisfied: werkzeug>=0.11.15 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (1.0.1)
Requirement already satisfied: wheel>=0.26 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (0.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (2.25.1)
Requirement already satisfied: markdown>=2.6.8 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (3.3.4)
Requirement already satisfied: absl-py>=0.4 in d:\newfolder\envs\frankmocap\lib\site-packages (from tensorboard->detectron2) (0.12.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in d:\newfolder\envs\frankmocap\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2) (4.2.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\newfolder\envs\frankmocap\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in d:\newfolder\envs\frankmocap\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in d:\newfolder\envs\frankmocap\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2) (1.3.0)
Requirement already satisfied: importlib-metadata in d:\newfolder\envs\frankmocap\lib\site-packages (from markdown>=2.6.8->tensorboard->detectron2) (3.10.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in d:\newfolder\envs\frankmocap\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2) (0.4.8)
Requirement already satisfied: chardet<5,>=3.0.2 in d:\newfolder\envs\frankmocap\lib\site-packages (from requests<3,>=2.21.0->tensorboard->detectron2) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\newfolder\envs\frankmocap\lib\site-packages (from requests<3,>=2.21.0->tensorboard->detectron2) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in d:\newfolder\envs\frankmocap\lib\site-packages (from requests<3,>=2.21.0->tensorboard->detectron2) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\newfolder\envs\frankmocap\lib\site-packages (from requests<3,>=2.21.0->tensorboard->detectron2) (1.26.4)
Requirement already satisfied: oauthlib>=3.0.0 in d:\newfolder\envs\frankmocap\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.4 in d:\newfolder\envs\frankmocap\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard->detectron2) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in d:\newfolder\envs\frankmocap\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard->detectron2) (3.4.1)

**(frankmocap) D:\video\2\1>  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.6/index.html
'https:' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by penincillin** [comment]
It seems that the detectron-2 still haven't been successfully installed. 
Would you mind try to raise the issue in Detectron-2 repo ? This issue seems to be related to operating system, which we haven't observed it on Linux.
