### ISSUE TITLE
how to add textures?

### ISSUE THREAD

**Issue by Adorablepet** [facebookresearch/frankmocap#101]
Thanks for you sharing codes, this is a greate project.But I have a question about how to add texture information to the 3D human body model, not `mesh_color`.Thanks again.If possible, can you give me a reference.

**Comment by penincillin** [comment]
For adding texture to SMPL / SMPL-X model, you can refer to this paper: [Texture-Pose](https://github.com/geopavlakos/TexturePose)

**Comment by Adorablepet** [comment]
thanks，I will try it.
