### ISSUE TITLE
save the output in video file

### ISSUE THREAD

**Issue by lan786** [facebookresearch/frankmocap#11]
Suggestion: It will be good if output can be saved in video file.

**Comment by penincillin** [comment]
@lan786 
Thanks for your suggestion, can you elaborate more ? What does it mean of saving the output in video file ?
The output means rendered images or predicted parameters ?
Again, thanks for your suggestion !

**Comment by jhugestar** [comment]
@lan786 

Done! 

https://github.com/facebookresearch/frankmocap/commit/ca6a8819c2383c1ca310d27e96f76d8a43ac5726

**Comment by lan786** [comment]
@penincillin My meaning was to save all the results in a video instead of frames/images. 
Thanks @jhugestar for updating it.
