### ISSUE TITLE
Macos installation

### ISSUE THREAD

**Issue by BenEcon** [facebookresearch/frankmocap#115]
My computer’s os is macOS, there is not option for apt-get to run “sudo apt-get install libosmesa6-dev”, how should I do to this?

**Comment by penincillin** [comment]
@BenEcon 
On macos, you can try to directly install opendr by run ```pip install opendr```.
Our code is pretended to be run on Linux with GPU. If you want to run it on macos, then you might need to care about other installation problem, too.

**Comment by BenEcon** [comment]
> @BenEcon
> On macos, you can try to directly install opendr by run `pip install opendr`.
> Our code is pretended to be run on Linux with Nvidia GPU and CUDA. If you want to run it on macos without CUDA support, you can refer to this [pull request](https://github.com/facebookresearch/frankmocap/pull/105)

Thank you. I will try it.
