### ISSUE TITLE
No module named demo  In Colab

### ISSUE THREAD

**Issue by AhmedShalabe** [facebookresearch/frankmocap#117]
When I try to execute this in colab
!xvfb-run -a python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output

I get 
/usr/bin/python3: Error while finding module specification for 'demo.demo_bodymocap' (ModuleNotFoundError: No module named 'demo')

**Comment by penincillin** [comment]
@AhmedShalabe 
I have a puzzle about the command you listed here. An ```!``` is added before ```xvfb-run```, would you mind double check this ?
Besides, this error seems to be related to the path, where do you run this command ? Is it within the project directory, i.e. ```frankmocap/``` ?

**Comment by AhmedShalabe** [comment]
@penincillin 
First I'd like to thank you for your great effort :)

![image](https://user-images.githubusercontent.com/85092229/120310925-32256200-c2d7-11eb-8a29-d52a4253e358.png)

this is used in colab 

As mentioned here in this issue
[https://github.com/facebookresearch/frankmocap/issues/28](url)

[https://colab.research.google.com/drive/15qA6kbyVK--8q88FHXdzwPiGT0UyKvwg?usp=sharing](url)
you have replied to this notebook written by Tikquuss

Thanks in advance :)

**Comment by AhmedShalabe** [comment]
> I have a puzzle about the command you listed here. An `!` is added before `xvfb-run`, would you mind double check this ?
> Besides, this error seems to be related to the path, where do you run this command ? Is it within the project directory, i.e. `frankmocap/` ?
@penincillin 
You are right 
when I command 
%cd /content/frankmocap
it says no such a directory

the problem was that you have to turn on GPU before executing the cloning 
!git clone https://github.com/facebookresearch/frankmocap.git

as when I turned on the GPU just before executing it gave me the error (no module found )
