### ISSUE TITLE
Detectron2 for Windows

### ISSUE THREAD

**Issue by FrankSpalteholz** [facebookresearch/frankmocap#122]
Hey there,

I hope that this is not a trivial question, but first of all thank you so much for this great repo! I've successfully got it to run on Windows10 with the BodyMocap-feature only since the link/implementation for Detectron2 is Linux only (as i understood). I've found this repo though https://github.com/conansherry/detectron2 and would like to ask if anyone got this running in combination with this repo here?
Thanks a lot!

**Comment by penincillin** [comment]
Hi,
Thanks for your interest in our work. The pre-built detectron2 files are available for Linux only. To use detectron2 on Windows, you might need to build it from source, I would suggest you to refer to the official document for details.
