### ISSUE TITLE
Is Interhand2.6m dataset used to train and test?

### ISSUE THREAD

**Issue by youngstu** [facebookresearch/frankmocap#123]
Is Interhand2.6m dataset used to train and test? Interhand2.6 dataset includes both one-hand and two-hand data sets, and the number is large. It may help to improve the generalization ability of the hand model.

**Comment by penincillin** [comment]
During we implement and train our hand modules, the InterHand2.6M is not released yet. Therefore, the training and testing data of InterHand2.6M are not used.
