### ISSUE TITLE
2D keypoints should be computed from root relative 3D keypoints or original 3D keypoints ?

### ISSUE THREAD

**Issue by youngstu** [facebookresearch/frankmocap#124]
2D keypoints should be computed from root relative 3D keypoints or original 3D keypoints ?
Frankmocap-hand shows that 2D keypoints are computed from root relative 3D keypoints.
Mobilehand shows that 2D keypoints are computed from original 3D keypoints.
https://github.com/facebookresearch/frankmocap/blob/0cb0578526eb0cb3eea919881ec32be253b34cd1/handmocap/hand_mocap_api.py#L208
https://github.com/gmntu/mobilehand/blob/db3ac7607d833b4d42c5261a464c7ff561357478/code/utils_neural_network.py#L106

**Comment by penincillin** [comment]
For frankmocap, the 2D keypoints are computed from original 3D keypoints regressed from body/hand meshes.

**Comment by youngstu** [comment]
For frankmocap, the 2D keypoints are computed from 3D keypoints shift.
https://github.com/facebookresearch/frankmocap/blob/0cb0578526eb0cb3eea919881ec32be253b34cd1/handmocap/hand_modules/h3dw_model.py#L211
