### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by hongsukchoi** [facebookresearch/frankmocap#130]
Hi, thanks for sharing your great work.

Does this repo contain training script? I am interested in blur augmentation you stated in the paper, but I can't find the corresponding codes.

**Comment by penincillin** [comment]
@hongsukchoi 
Thanks for your asking. We are considering releasing the training code but the date is not determined yet.
You are welcomed to send emails to me to ask for training details. My email address can be easily found in my github main page.

**Comment by penincillin** [comment]
@hongsukchoi

**Comment by hongsukchoi** [comment]
@penincillin 

Hi, I sent you an email about the augmentation code, but did not get answer yet...
Could you check it out?
