### ISSUE TITLE
Which datasets you are using for Egocentric Hand Motion Capture?

### ISSUE THREAD

**Issue by OOF-dura** [facebookresearch/frankmocap#131]
Hi~ Thank you for your great work!
May I know which datasets you are using for Egocentric Hand Motion Capture?

Thanks!

**Comment by penincillin** [comment]
All datasets we used to train our models are listed in the paper. 
You do not use any egocentric-specific dataset to train our models, due to the lack of annotations. But I think our algorithm is compatible with the egocentric datasets, you can try to add them in training.
