### ISSUE TITLE
How to get 3D hand joints position coordinate under the camera system?

### ISSUE THREAD

**Issue by buaacyw** [facebookresearch/frankmocap#133]
Thanks for your great work! And I have a question:
**I have the camera intrinsic of the input image and want to get hand joints position coordinate under the camera system** 

I have read [joint order](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md) in your doc and the code in [hand_mocap_api.py](https://github.com/facebookresearch/frankmocap/blob/0cb0578526eb0cb3eea919881ec32be253b34cd1/handmocap/hand_mocap_api.py#L208).

I find that your regressor outputs the hand joints position under SMPL 3D coordinate and then you convert them in the order of SMPL 3D coordinate <-> 2D bounding box coordinate<-> original 2D image coordinate. And the Z axes of these different representations are all relative values. As can be seen below, the 5(Index_00) is the origin point.

<img width="337" alt="WeChat58356b37945daef7270bb75b27715c06" src="https://user-images.githubusercontent.com/52091468/122368676-20f37b00-cf90-11eb-97c3-074d4e20e1ae.png">

So I don't know how to get the 3D hand joints position coordinate under the camera system since I don't know the Z axes value of the joint Index_00.

Please help me, thanks for your work again!

**Comment by penincillin** [comment]
@buaacyw 
That's a good question. Our models (both body and hand) only predicts relative 3D coordinates, with root set to zero. 
To obtain absolute coordinates under camera space, I recommend [RootNet](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE).

**Comment by buaacyw** [comment]
@penincillin 
Thanks for your reply. But RootNet can't be applied on hands.

**Comment by Arpitrf** [comment]
@buaacyw Have you tried RootNet with hands? Was wondering why it can't be applied to hands?
