### ISSUE TITLE
About hand pose

### ISSUE THREAD

**Issue by YuyanHuang** [facebookresearch/frankmocap#136]
1. Is `pred_hand_pose` the local axis-angle? Contains wrist and fingers.
2. Is the pose of the dataset FreiHand and HO3D the local axis-angle? Contains wrist and fingers.

**Comment by penincillin** [comment]
1. ```pred_hand_pose``` is represented in relative/local axis-angle.
2. Annotations of FreiHand and HO3D are also axis-angle. One thing to note is that the input pose parameters of SMPL-X (MANO) model is not exact the joint angles but the joint angles minus mean joint angles. I refer to check [origin code](https://github.com/vchoutas/smplx/blob/43561ecabd23cfa70ce7b724cb831b6af0133e6e/smplx/body_models.py#L1504) for details. Based on this, FreiHand annotations are joint_angles - mean while HO3D annotations are origin joint_angles.

**Comment by penincillin** [comment]
Question-2 is a little bit tricky. I would suggest you to visualize the FreiHand annotations and HO3D annotations, using the SMPL-X's official implementation instead of the implementation provided by these two datasets. Please feel free to raise question here if you encounter with any problems.

**Comment by YuyanHuang** [comment]
When supervising the axis-angle, have you supervised the wrist joints?

**Comment by penincillin** [comment]
@YuyanHuang 
Following the practice of previous works (HMR etc), we do not supervise wrist joints in either 3D joint loss or axis-angle loss.
The reason for not supervising 3D joint is that we only predicts relative 3D joints and wrist is used as the root.
The reason for not supervising axis-angle is that rotation of wrist is the rotation of overall hands.  However, overall hand rotation is correlated to camera intrinsic, which is agnostic in our setting. Therefore, we do not apply axis-angle supervision on wrist rotations. Besides, we have done experiments to incorporate wrist incorporating during training, the performances are not improved.
