### ISSUE TITLE
Do you have the papers or technical details documents ...

### ISSUE THREAD

**Issue by yangjituan** [facebookresearch/frankmocap#137]
Hi, thanks for your wonderful work!
I wonder if there is a paper or some technical documents about your project?

**Comment by penincillin** [comment]
Thanks for your interest in our work. [Our paper](https://arxiv.org/pdf/2008.08324.pdf) can be found on arxiv. We will update a new paper recently.

**Comment by yangjituan** [comment]
Thank you! 
Looking forward to your new paper.

**Comment by penincillin** [comment]
@yangjituan 
Our paper is accepted to ICCV Workshop 2021. It is preferred to refer/cite our new paper. The [new paper](https://arxiv.org/abs/2108.06428) and [new bibtex](https://arxiv.org/abs/2108.06428).
