### ISSUE TITLE
Unsupported function 'torch.cross' in "BodyMocap-->model_regressor-->hmr"?

### ISSUE THREAD

**Issue by yangjituan** [facebookresearch/frankmocap#138]
Hi, 
I'm trying to convert the  model for libtorch use:
![image](https://user-images.githubusercontent.com/53220351/123726489-a9441b00-d8c2-11eb-8edb-f5e396b1d00f.png)

but the model i got have a bug  calls "Unsupport function 'torch.cross'"  and i haven't seen any torch.cross in your code.

**Comment by penincillin** [comment]
torch.cross is used [here](https://github.com/facebookresearch/frankmocap/blob/0cb0578526eb0cb3eea919881ec32be253b34cd1/mocap_utils/geometry_utils.py#L185)

**Comment by yangjituan** [comment]
Got it, Thanks very much!
