### ISSUE TITLE
Axis-angle coordinate system direction

### ISSUE THREAD

**Issue by YuyanHuang** [facebookresearch/frankmocap#139]
`docs/joint_order.md` gives the axis-angle coordinate direction of `pred_hand_pose` as:
![image](https://user-images.githubusercontent.com/32838998/124448659-45838b80-ddb5-11eb-9ddc-ef4c9c813431.png)
But I found through [smplx](https://github.com/vchoutas/smplx/blob/master/examples/demo.py) that its T-pose is:
![image](https://user-images.githubusercontent.com/32838998/124455899-ad89a000-ddbc-11eb-8fa8-dd43830dab93.png)
![image](https://user-images.githubusercontent.com/32838998/124456056-dad64e00-ddbc-11eb-9e41-6ef390f72fb4.png)
But if it is in the direction of the above coordinate system, then the human body will be upside down?

**Comment by penincillin** [comment]
@YuyanHuang 
Interesting, when I set zero-poses, the resulting human poses are truly upside down. 
I guess the discrepancy is caused by the different coordinate system cross different renderer.

**Comment by YuyanHuang** [comment]
@penincillin 
So the real coordinate direction of the “wrist axis-angle” of `pred_hand_pose` is indeed: 
![image](https://user-images.githubusercontent.com/32838998/124543674-47525b00-de58-11eb-8227-8a7587333941.png)

In addition, I calculated the direction vector of the hand and palm based on some key points of `pred_joints_smpl`, and then calculated the axis-angle of the wrist based on these two vectors, and found that it is very different from the wrist axis-angle of `pred_hand_pose`. The included angle is greater than 100 degrees.

`pred_joints_smpl` is calculated based on `pred_hand_pose`, why is there such a big difference between the two wrist axis-angles？Thank you!

**Comment by penincillin** [comment]
@YuyanHuang 
First, the axis-angle values ``pred_hand_pose`` is the relative rotation. For wrist angle, it is the rotation relative to the parent of wrist in the kinematics which is the elbow. You might need to double check whether the axis-angle you calculated from ``pred_joints_smpl`` is the global rotation are relative rotation.
Second, the axis-angle has ambiguity, two vectors with different values can represent the same rotation. You might also need to check this.
