### ISSUE TITLE
How can i adapt the output of the project to 3D characters with 3D model creation programs?

### ISSUE THREAD

**Issue by serdarhakimoglu** [facebookresearch/frankmocap#14]
Hi, thanks for this amazing work.

I want to adapt the output of the project to 3D characters with 3D model creation programs like Blender, Maya etc.
Is this possible, what should i do?
Can i take keypoints coordinates, if i use the "save_pred_pkl" argument?

And there is an argument named "save_mesh".
I am using this argument, but it doesn't give an output?
What should we use this argument for?

Also in OpenGL GUI visualization mode, the j key is not toggle skeleton visualization.
Am I doing something wrong?

Thanks again.

**Comment by jhugestar** [comment]
Thanks for your questions. 

- We plan to add a pipeline to export our output to a standard mocap format (e.g., BVH). 
- We haven't implemented the save_mesh pipeline yet. 

I think we can update above things around Dec.

**Comment by ZerRui** [comment]
Looking forward to your update!

**Comment by ZerRui** [comment]
> Thanks for your questions.
> 
> * We plan to add a pipeline to export our output to a standard mocap format (e.g., BVH).
> * We haven't implemented the save_mesh pipeline yet.
> 
> I think we can update above things around Dec.

Looking forward to your update!
