### ISSUE TITLE
Importing .pkl data into Houdini?

### ISSUE THREAD

**Issue by ryanmross** [facebookresearch/frankmocap#140]
Has anyone had any luck importing the .pkl data into Houdini?  I'm working on a python script that imports it, but am running into a couple issues:
* I was able to import joint position in and apply it to a skeleton (though the data comes in upside down)
* I was able to get FrankMocap to export out pred_rotmat for each body joint with the idea of applying it as a transform9 to each body joint, but I'm not showing that the data is correctly aligning yet.  Are these rotations relative based on the hierarchy of the skeleton? (like do the hip rotations need to have the pelvis/root rotation added to it, and the leg rotations need the hip rotations added to them, etc?)
* I was able to import the hand joint positions
* But I'm really struggling to get hand joint rotations to work correctly.  I have the "pred_lhand_pose" data importing, but it's coming in as what looks to be 3 floats per joint (in angle-axis format?)  And from what I can tell, angle-axis format needs 4 floats (3 for the axis vector and 1 for the angle, right?)  And are these meant to be relative rotations based off of the wrist's rotation?

Thanks!

**Comment by penincillin** [comment]
@ryanmross 
Thanks for your interest in our work and providing the detailed descriptions. My replies are:

- Joint rotations are relative 3D rotation (either in rotation matrix or axis-angle) based on the kinematic tree (or say hierarchy of the skeleton). The hierarchy of body joints are depicted [here](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md#joint-angle-body). The hierarchy of hand joints are listed [here](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md#joint-angle-hand)

**Comment by ryanmross** [comment]
Thanks! Also I had another question— how come there’s is a discrepancy between the joints in the joint position list and the joints that are in the joint angles list? Are there certain joints in the joints position list that correspond to the ones in the joint angles list?

**Comment by penincillin** [comment]
@ryanmross 
You are correct. The order of joint positions and joint angles are different. You may refer to the [joint_order](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md) for detailed orders of body/hand joint positions/rotations.

**Comment by ryanmross** [comment]
So for example, in the body joint angles list, there are listed Spine_01, Spine_02, and Spine_03.  Which body joint positions would correspond to these?

**Comment by penincillin** [comment]
@ryanmross 
The joint positions listed in readme or not the original 3D joints from SMPL model. They are obtained by reordering the original joints and regressing new joints. You can use ```smpl_output.joints``` obtained from [here](https://github.com/facebookresearch/frankmocap/blob/0cb0578526eb0cb3eea919881ec32be253b34cd1/bodymocap/models/smpl.py#L40) to get the original joints whose order is the same as the order of joint angles.
