### ISSUE TITLE
Issue while running Frankmocap 

### ISSUE THREAD

**Issue by antonioia9** [facebookresearch/frankmocap#143]
Hi, i have this error while running Frankmocap from Anaconda Prompt:
File "C:\MOCAP\frankmocap\demo\demo_frankmocap.py", line 228, in main
assert torch.cuda.is_available(), "Current version only supports GPU"
AssertionError: Current version only supports GPU

my gpu is amd radeon 535, is it possible to run frankmocap whit this gpu??

**Comment by penincillin** [comment]
@antonioia9 
Current code cannot support an AMD GPU. You may check to this [pull request](https://github.com/facebookresearch/frankmocap/pull/103) to use CPU.
