### ISSUE TITLE
Error while running frankmocap only with image

### ISSUE THREAD

**Issue by antonioia9** [facebookresearch/frankmocap#148]
Hi everyone, I have this error while running frankmocap with an image. If I analyze a video, it works normally, but if I analyze an image it shows me this. Can anyone tell me why?

(frankmocap) C:\MOCAP\frankmocap>python -m demo.demo_frankmocap_CPU_BETA --input_path ./sampledata/frank.jpg --out_dir ./mocap_output
Loading Body Pose Estimator
Loading Third View Hand Detector
Traceback (most recent call last):
  File "C:\Users\PRINCIPAL\anaconda3\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\PRINCIPAL\anaconda3\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\MOCAP\frankmocap\demo\demo_frankmocap_CPU_BETA.py", line 250, in <module>
    main()
  File "C:\MOCAP\frankmocap\demo\demo_frankmocap_CPU_BETA.py", line 244, in main
    run_frank_mocap_cpu(args, hand_bbox_detector, body_mocap, hand_mocap,visualizer)
  File "C:\MOCAP\frankmocap\demo\demo_frankmocap_CPU_BETA.py", line 111, in run_frank_mocap_cpu
    input_type, input_data = demo_utils.setup_input(args)
  File "C:\MOCAP\frankmocap\mocap_utils\demo_utils.py", line 101, in setup_input
    input_type = __get_input_type(args)
  File "C:\MOCAP\frankmocap\mocap_utils\demo_utils.py", line 55, in __get_input_type
    assert False, "Unknown input path. It should be an image," + \
AssertionError: Unknown input path. It should be an image,or an image folder, or a video file, or 'webcam'

**Comment by penincillin** [comment]
@antonioia9 
Actually, the input format of directly using image paths are not supported. We apologize for the misleading information in the previous documents. To run the code on images, you should set the ```input_path``` to the ```path of folder containing the input images```. In your case, you should use ```--input_path ./sampledata```.

**Comment by antonioia9** [comment]
Thank you! I wrote --input_path ./sampledata/... .jpg and it doesn't run. So I can only run frankmocap from videos?

**Comment by penincillin** [comment]
@antonioia9 
You should use ```--input_path path_of_folder_storing_your images```. For example, suppose the path of your images are put in ```sampledata/images/xxx.jpg```, then you should set ```--input_path sampledata/images```.

**Comment by flynnamy** [comment]
How about this problem? @penincillin 
![image](https://user-images.githubusercontent.com/20398890/129154824-441fb825-38aa-4abc-b5e7-31fc0406abb2.png)

**Comment by penincillin** [comment]
@flynnamy 
This error seems to be caused by OpenGL. Are you trying to use OpenGL on the server ?
