### ISSUE TITLE
what does OP mean in OP_NOSE, OP_NECK...?

### ISSUE THREAD

**Issue by antonioia9** [facebookresearch/frankmocap#149]
Hi, this is the joints order, I'd like to know what does OP_ stand for and what is the difference between OP_L_KNEE and L_KNEE , OP_R_KNEE and R_KNEE etc..

0: OP_Nose
1: OP_Neck
2: OP_R_Shoulder
3: OP_R_Elblow
4: OP_R_Wrist
5: OP_L_Shoulder
6: OP_L_Elbow
7: OP_L_Wrist
8: OP_Middle_Hip
9: OP_R_Hip
10: OP_R_Knee
11: OP_R_Ankle
12: OP_L_Hip
13: OP_L_Knee
14: OP_L_Ankle
15: OP_R_Eye
16: OP_L_Eye
17: OP R_Ear
18: OP_L_Ear
19: OP_L_Big_Toe
20: OP_L_Small_Toe
21: OP_L_Heel
22: OP_R_Big_Toe
23: OP_R_Small_Toe
24: OP_R_Heel
25: R_Ankle
26: R_Knee
27: R_Hip
28: L_Hip
29: L_Knee
30: L_Ankle
31: R_Wrist
32: R_Elbow
33: R_Shoulder
34: L_Shoulder
35: L_Elbow
36: L_Wrist
37: Neck (LSP)
38: Top of Head (LSP)
39: Pelvis (MPII)
40: Thorax (MPII)
41: Spine (H36M)
42: Jaw (H36M)
43: Head (H36M)
44: Nose
45: L_Eye
46: R_Eye
47: L_Ear
48: R_Ear

**Comment by penincillin** [comment]
```OP``` refers to ```OpenPose```
