### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by jiuney** [facebookresearch/frankmocap#15]
Hello,

I'm a novice in this field, and I tried to follow the installation guide, but I encountered problems when I tried to install required packages using requirements.txt file.
Error message says that it failed to build opendr, and then bunch of other error messages in red which basically says that it can't install other things as well.
I tried to google the solution, and it seems that many others are also having trouble installing opendr and using opendr with python3 (some says that opendr only works with python2).
Can you plz help me?

**Comment by penincillin** [comment]
Hi Jiuney,

We offer other visualization method. Can you try to install pytorch3d and use it for rendering ?

**Comment by jiuney** [comment]
Hi penincillin,

Thank you for your response which was much faster than I expected.
I will try pytorch3d and let you know how it turns out.

Thanks!

**Comment by MolianWH** [comment]
@jiuney  I tried this way to install opendr and it works.
Install opendr should firstly install some dependent envs:
```shell
sudo apt-get install libosmesa6-dev \
build-essential \
libgl1-mesa-dev \
libglu1-mesa-dev \
freeglut3-de
```
Then , make soft link file to your own conda envs
```shell
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1 /home/username/anaconda3/envs/venv_frankmocap/lib/libGL.so
```
And install opendr
```shell
$ pip install opendr
```

**Comment by jiuney** [comment]
@MolianWH Thank you for your suggestion! Actually, when I googled solutions to the opendr problem, I saw that method elsewhere (https://github.com/akanazawa/hmr/issues/82#issuecomment-557430371) and tried it, but it didn't work for me. Error messages said that libosmesa6-dev is not found in their channel, so I added conda-forge channel but failed. Anyways, thank you for your help :)

And, as @penincillin suggested, I tried installing pytorch3d and it worked fine. But then I realized that the original detectron2 doesn't support windows10, so I'm having another problem. But it's not related to opendr problem, so I'm going to close this issue. My last question is, does frankmocap support usage on windows10? I'm now installing detectron2 for windows (https://github.com/conansherry/detectron2), but if frankmocap doesn't work on windows it won't work anyway.

**Comment by penincillin** [comment]
@MolianWH Thanks for sharing your solution here !

**Comment by penincillin** [comment]
@jiuney 
Sorry, we don't support windows-10 yet. But detectron2 is not that necessary depending on your aim.
Would you mind tell me which kind of motion capture are you trying to perform ? It's hand-only, body-only or body-plus-hand

**Comment by jiuney** [comment]
@penincillin I definitely need body pose estimation, but I  haven't decided whether I would use hand motion or not. If I decide to use body motion only, do you think it may be okay to install and run frankmocap on Windows10?

**Comment by jhugestar** [comment]
Hi @jiuney, we do not have windows machine to test, so unfortunately do not have a good answer. Could you maybe please try and share if you can find good solutions? It would be very helpful for other users in the similar situation! Thanks!

**Comment by penincillin** [comment]
@jiuney 
Detectron2 is only required for hand detection. Therefore, if you only need body motion capture, then it is unnecessary.
Would you mind try to run demo_bodymocap.py without detectron2 installation ?

**Comment by jiuney** [comment]
I'm trying to use Linux but faced so many errors installing frankmocap so I couldn't try testing on Windows. So I'm closing this issue. Thank you all for your support.
