### ISSUE TITLE
No module named 'demo'

### ISSUE THREAD

**Issue by Christopeos** [facebookresearch/frankmocap#151]
I get this error when running the bodymocap:

Error while finding module specification for 'demo.demo_bodymocap' (ModuleNotFoundError: No module named 'demo')

**Comment by penincillin** [comment]
This seems to be a path issue. Under which directory do you run the script or the code ?

**Comment by Christopeos** [comment]
Apparently python couldn't access the subfolder where everything was, i moved the files and now it works all right. Thank you.
