### ISSUE TITLE
adjusting sensitivty in pose detection

### ISSUE THREAD

**Issue by Drom0s137** [facebookresearch/frankmocap#153]
I managed to run the demo but when running a custom video, I am getting a lot of noise. random corners are being recognized as poses and its annoying. Is there a way for me to change the sensitivity in the demo code for demo_bodymocap.py?

**Comment by penincillin** [comment]
@Drom0s137  Would you mind share your source images or videos to me ? So that I can check it for you.
Otherwise, I suggest you to try to using off-the-shelf method to obtain body bbox. The suggested one are open-pose or some faster r-cnn based detectors.
