### ISSUE TITLE
Error in handmocap demo

### ISSUE THREAD

**Issue by gyfastas** [facebookresearch/frankmocap#156]
Hi! Thank you for your great work! I tried running handmocap demo on windows (after following the installation guideline provided by https://github.com/carlosedubarreto/frankmocap_win_install ) and found it raises error in `handmocap/hand_bbox_detector.py` : 

line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'

Then I tried using `from detectors.hand_object_detector.lib.model.utils.config import cfg as cfgg` but it still does not works. The error is as follows:

frankmocap\detectors\hand_object_detector\lib\model\roi_layers\nms.py", line 3, in <module>
    from model import _C
ModuleNotFoundError: No module named 'model'

Could you provide some suggestions? I'm a little bit confused by the importing

**Comment by sunmengnan** [comment]
> hand_object_detector

where is hand_object_detector?

**Comment by penincillin** [comment]
@sunmengnan 
It is at ```./detectors/hand_object_detector```.

**Comment by liuhaorandezhanghao** [comment]
> @sunmengnan It is at `./detectors/hand_object_detector`.

(venv) [root@algo-10-143-1-10 frankmocap-main]# python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output --renderer_type pytorch3d
Loading Body Pose Estimator
use_smplx False
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Cannot import OpendrRenderer
Cannot import Pytorch3dRenderer
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vtuber/project/frankmocap/frankmocap-main/demo/demo_bodymocap.py", line 178, in <module>
    main()
  File "/home/vtuber/project/frankmocap/frankmocap-main/demo/demo_bodymocap.py", line 169, in main
    from renderer.screen_free_visualizer import Visualizer
  File "/home/vtuber/project/frankmocap/frankmocap-main/renderer/screen_free_visualizer.py", line 25, in <module>
    assert g_valid_visualize, "You should import either OpenDR or Pytorch3D"
AssertionError: You should import either OpenDR or Pytorch3D

**Comment by penincillin** [comment]
@liuhaorandezhanghao 
It seems that the opendr or pytorch3d is not correctly installed. Would you min check [line-14](https://github.com/facebookresearch/frankmocap/blob/1c0f78907e82f95e183ecae20f6a70226c7c7a18/renderer/screen_free_visualizer.py#L14) and [line-20](https://github.com/facebookresearch/frankmocap/blob/1c0f78907e82f95e183ecae20f6a70226c7c7a18/renderer/screen_free_visualizer.py#L20) to see whether the rendering packages are successfully installed.
