### ISSUE TITLE
The lower extremity demo_frankmocap

### ISSUE THREAD

**Issue by khalidlionel** [facebookresearch/frankmocap#163]
I tried an image with only the upper extremity  (so The lower extremity is hidden) but lower extremity is shown uncorrectly.
can we remove the lower extremity in this case?

**Comment by khalidlionel** [comment]
By the way demo_bodymocap handled this issue..
But i need the hand prediction also.

**Comment by penincillin** [comment]
@khalidlionel 
Would you mind sharing an example? I am a little puzzled.
