### ISSUE TITLE
opengl error

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [facebookresearch/frankmocap#164]
(venv) [root@algo-10-143-1-10 frankmocap-main]# python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Loading Body Pose Estimator
Loading Third View Hand Detector
The checkpoint state_dict contains keys that are not used by the model:
  proposal_generator.anchor_generator.cell_anchors.{0, 1, 2, 3, 4}
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vtuber/project/frankmocap/frankmocap-main/demo/demo_frankmocap.py", line 247, in <module>
    main()
  File "/home/vtuber/project/frankmocap/frankmocap-main/demo/demo_frankmocap.py", line 241, in main
    visualizer = Visualizer(args.renderer_type)
  File "/home/vtuber/project/frankmocap/frankmocap-main/renderer/visualizer.py", line 48, in __init__
    self.renderer = meshRenderer.meshRenderer()
  File "/home/vtuber/project/frankmocap/frankmocap-main/renderer/meshRenderer.py", line 37, in __init__
    glRenderer.__init__(self, width, height, name, self.program_files[render_mode], color_size, ms_rate)
  File "/home/vtuber/project/frankmocap/frankmocap-main/renderer/glRenderer.py", line 27, in __init__
    glutInit()
  File "/home/vtuber/venv/lib/python3.6/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "/home/vtuber/venv/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

**Comment by penincillin** [comment]
@liuhaorandezhanghao 
Please set the flag ``--renderer_type pytorch3d``.

**Comment by liuhaorandezhanghao** [comment]
> @liuhaorandezhanghao Please set the flag `--renderer_type pytorch3d`.

but pytorch3d only support mac so i can not use cuda=10.1/torch=1.6 .and now i hava a new error:freeglut (foo): failed to open display 'unix:1'.thanks for your reply.

**Comment by penincillin** [comment]
@liuhaorandezhanghao 
I am a little puzzled. According to the official guidance of Pytorch-3D (attached below). It supports both Mac and GPU.
![image](https://user-images.githubusercontent.com/11267794/141399948-c6fe8661-c165-4779-953c-60649201e91b.png)

**Comment by liuhaorandezhanghao** [comment]
Hello, isn't the result of frankmocap based on smplx? Why does smplx's hand only have 15 bone points, while the output of the algorithm has 21.




On 11/12/2021 10:43，Yu ***@***.***> wrote：

@liuhaorandezhanghao
I am a little puzzled. According to the official guidance of Pytorch-3D (attached below). It supports both Mac and GPU.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuhaorandezhanghao** [comment]
I got it, thanks,don’t reply this email.




On 11/16/2021 ***@***.***> wrote：
Hello, isn't the result of frankmocap based on smplx? Why does smplx's hand only have 15 bone points, while the output of the algorithm has 21.




On 11/12/2021 10:43，Yu ***@***.***> wrote：

@liuhaorandezhanghao
I am a little puzzled. According to the official guidance of Pytorch-3D (attached below). It supports both Mac and GPU.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
