### ISSUE TITLE
ModuleNotFoundError: No module named 'model'  error

### ISSUE THREAD

**Issue by Lruidong** [facebookresearch/frankmocap#167]
this is my environment      python3.7+pytorch1.10+cuda11.3+cudnn8.0.  ..   
there are some problem  ，please help me ，think！
run ` python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output   `  
Visualization saved: ./mocap_output/rendered/00182.jpg
Time: 0.36 sec/frame, FPS 2.78
Processed : ./mocap_output/frames/00182.jpg
>> Generating video in ./mocap_output/han_short.mp4
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
  configuration: --prefix=/home/server/anaconda3/envs/v_frank --cc=/opt/conda/conda-bld/ffmpeg_1597178665428/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-pic --enable-pthreads --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
Unrecognized option 'x264opts'.
Error splitting the argument list: Option not found
run `python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output`
(v_frank) root@server-System-Product-Name:/home/ruid/frankmocap# python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Traceback (most recent call last):
  File "/home/server/anaconda3/envs/v_frank/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/server/anaconda3/envs/v_frank/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ruid/frankmocap/demo/demo_frankmocap.py", line 24, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/ruid/frankmocap/handmocap/hand_bbox_detector.py", line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'

**Comment by rlleshi** [comment]
I think that this is a problem with your installation. At least it was so in my case.

**Comment by penincillin** [comment]
@Lruidong 
It seems that the hand detector is not successfully installed. Would you mind following this [hand detector installation script](https://github.com/facebookresearch/frankmocap/blob/main/scripts/install_hand_detectors.sh) step-by-step to install the hand detectors?

**Comment by Lruidong** [comment]
> @Lruidong 看来手部检测器没有安装成功。您介意按照此[手部探测器安装脚本](https://github.com/facebookresearch/frankmocap/blob/main/scripts/install_hand_detectors.sh)逐步安装手部探测器吗？
