### ISSUE TITLE
Bound box threshold 

### ISSUE THREAD

**Issue by rlleshi** [facebookresearch/frankmocap#168]
Could you please point me to how one can set the bounding box thresholds for both body and hand recognition models?

Found a bunch of thresholds [here](https://github.com/facebookresearch/frankmocap/blob/main/bodymocap/utils/imutils.py) but didn't really notice a difference from the tests. Otherwise, [this](https://github.com/facebookresearch/frankmocap/blob/1c0f78907e82f95e183ecae20f6a70226c7c7a18/handmocap/hand_bbox_detector.py#L56) one and [this](https://github.com/facebookresearch/frankmocap/blob/1c0f78907e82f95e183ecae20f6a70226c7c7a18/handmocap/hand_bbox_detector.py#L247) one seems to be used for thresholding of the hand but I didn't notice (any) effect.

**Comment by penincillin** [comment]
@rlleshi 
You can set the threshold by adjusting the two variables you mentioned.
