### ISSUE TITLE
Questions about the correspondence between the hand joint points and the smplx model

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [facebookresearch/frankmocap#169]
It can be seen from the code that there are 21 bone points in the hand,such as:
0 : Wrist
1 : Thumb_00
2 : Thumb_01
3 : Thumb_02
4 : Thumb_03
5 : Index_00
6 : Index_01
7 : Index_02
8 : Index_03
9 : Middle_00
10 : Middle_01
11 : Middle_02
12 : Middle_03
13 : Ring_00
14 : Ring_01
15 : Ring_02
16 : Ring_03
17 : Little_00
18 : Little_01
19 : Little_02
20 : Little_03
But in smplx, there are only 15 joint points, can anyone tell me how these joint points correspond?
The following is a comparison between my posture in smplx and the actual posture
![image](https://user-images.githubusercontent.com/45560746/142177756-c82c6b5c-91d4-4c93-a793-bbde1e7b005d.png)
![image](https://user-images.githubusercontent.com/45560746/142177804-6247498f-0bfc-49d5-be3d-d45d9b49567e.png)

**Comment by penincillin** [comment]
@liuhaorandezhanghao 
Please be noted that the word **joint** has two meanings. The first one is **joint positions** and the second one is **joint angle** or say **joint rotations**. The original SMPL-X only have 15 joint positions and joint angles. We extend it to 21 joints with 5 additional tip joints. The order of **joint positions** and **joint angles** are listed [here](https://github.com/facebookresearch/frankmocap/blob/main/docs/joint_order.md)

**Comment by liuhaorandezhanghao** [comment]
I have completely followed the instructions [here](https://github.com/facebookresearch/frankmocap/blob/main/docs/joint_order.md) to correspond to the joints of the hand and the body (the expression of the axis angle, using'pred_right_hand_pose'), but the result is still not quite right. Can you provide some suggestions?

**Comment by liuhaorandezhanghao** [comment]
> 我已经完全按照[这里](https://github.com/facebookresearch/frankmocap/blob/main/docs/joint_order.md)的说明来对应手和身体的关节（轴角的表达，使用'pred_right_hand_pose'），但结果仍然不太正确。你能提供一些建议吗

我已经完全按照这里的说明来对应手和身体的关节（轴角的表达，使用'pred_right_hand_pose'），但结果仍然不太正确。你能提供一些建议吗

**Comment by liuhaorandezhanghao** [comment]
> I have completely followed the instructions [here](https://github.com/facebookresearch/frankmocap/blob/main/docs/joint_order.md) to correspond to the joints of the hand and the body (the expression of the axis angle, using'pred_right_hand_pose'), but the result is still not quite right. Can you provide some suggestions?

I have completely followed the instructions here to correspond to the joints of the hand and the body (the expression of the axis angle, using'pred_right_hand_pose'), but the result is still not quite right. Can you provide some suggestions?

**Comment by liuhaorandezhanghao** [comment]
@penincillin

**Comment by penincillin** [comment]
@liuhaorandezhanghao 
In the shown figures, the figure-1 generates reasonable results while figure-2 contains twisted fingers. Would you mind tell me how do you obtain the figure-2. Did you use the predicted hand pose parameters from our code and fed them into the mano model from other code?

**Comment by liuhaorandezhanghao** [comment]
> @liuhaorandezhanghao 请注意，**联合**一词有两个含义。第一个是**关节位置**，第二个是**关节角度**或说**关节旋转**。原来的 SMPL-X 只有 15 个关节位置和关节角度。我们将其扩展到 21 个关节和 5 个额外的尖端关节。[此处](https://github.com/facebookresearch/frankmocap/blob/main/docs/joint_order.md)列出了**关节位置**和**关节角度**的顺序。[](https://github.com/facebookresearch/frankmocap/blob/main/docs/joint_order.md)

I have completely followed the instructions here to correspond to the joints of the hand and the body (the expression of the axis angle, using'pred_right_hand_pose'), but the result is still not quite right. Can you provide some suggestions?
![image](https://user-images.githubusercontent.com/45560746/143392271-c4c94f3d-7d4c-42a1-a354-7dcd9914c0ff.png)

**Comment by penincillin** [comment]
@liuhaorandezhanghao 
Please answer my question first. How do you obtain the third image/result, as this visualization is not generated from our code.

**Comment by liuhaorandezhanghao** [comment]
> > @liuhaorandhanghao请注意，**联合**电影有两个特点。第一个是**关节位置**，第二个是**关节**说的**关节旋转**。原来的SMPLX只有我们15个关节位置和关节角度。将其扩展到21个关节和5个额外的尖端关节。[此处](https://github.com/facebookresearch/frankmocap/blob/main/docs/joint_order.md)列出了**关节位置**状语从句：**关节角度**的顺序。
> 
> 我已经完全按照这里的说明来对应手和身体的关节（轴角的表达，使用'pred_right_hand_pose'），但结果仍然不太正确。你能提供一些建议吗？ ![图片](https://user-images.githubusercontent.com/45560746/143392271-c4c94f3d-7d4c-42a1-a354-7dcd9914c0ff.png)

Hello, I wrote the body and hand parameters predicted by the code into the smplx model in unity. According to the document, the order of the joints is corresponding. There should be nothing wrong.

**Comment by liuhaorandezhanghao** [comment]
> @liuhaorandezhanghao 请先回答我的问题。您如何获得第三个图像/结果，因为此可视化不是从我们的代码生成的。

The third result is obtained by passing the predicted body and posture parameters to unity's smplx model。

**Comment by penincillin** [comment]
@penincillin 
The issue of the finger poses are high likely to be related to the issue of mean parameters of MANO models. The mean parameters is a 45-dim vectors as 
```
array([ 0.11167872, -0.04289217,  0.41644184,  0.10881133,  0.06598568,
        0.75622001, -0.09639297,  0.09091566,  0.18845929, -0.11809504,
       -0.05094385,  0.5295845 , -0.14369841, -0.0552417 ,  0.70485714,
       -0.01918292,  0.09233685,  0.33791352, -0.45703298,  0.19628395,
        0.62545753, -0.21465238,  0.06599829,  0.50689421, -0.36972436,
        0.06034463,  0.07949023, -0.14186969,  0.08585263,  0.63552826,
       -0.30334159,  0.05788098,  0.63138921, -0.17612089,  0.13209308,
        0.37335458,  0.85096428, -0.27692274,  0.09154807, -0.49983944,
       -0.02655647, -0.05288088,  0.53555915, -0.04596104,  0.27735802])
```
Please add (or subtract) these mean parameters to the predicted pose parameters from our code. It should be able to solve your problem.

**Comment by liuhaorandezhanghao** [comment]
> 596104,  0.27735802])

thx,i will try it。but i used unity ,it seems like mano?

**Comment by liuhaorandezhanghao** [comment]
> @penincillin 手指姿势问题很可能是由 MANO 模型的平均参数引起的。平均参数是一个 45 维向量，如下所示：
> 
> ```
> right-hand:
> array([ 0.11167872, -0.04289217,  0.41644184,  0.10881133,  0.06598568,
>         0.75622001, -0.09639297,  0.09091566,  0.18845929, -0.11809504,
>        -0.05094385,  0.5295845 , -0.14369841, -0.0552417 ,  0.70485714,
>        -0.01918292,  0.09233685,  0.33791352, -0.45703298,  0.19628395,
>         0.62545753, -0.21465238,  0.06599829,  0.50689421, -0.36972436,
>         0.06034463,  0.07949023, -0.14186969,  0.08585263,  0.63552826,
>        -0.30334159,  0.05788098,  0.63138921, -0.17612089,  0.13209308,
>         0.37335458,  0.85096428, -0.27692274,  0.09154807, -0.49983944,
>        -0.02655647, -0.05288088,  0.53555915, -0.04596104,  0.27735802])
> 
> left-hand:
> array([ 0.11167872,  0.04289217, -0.41644184,  0.10881133, -0.06598568,
>        -0.75622001, -0.09639297, -0.09091566, -0.18845929, -0.11809504,
>         0.05094385, -0.5295845 , -0.14369841,  0.0552417 , -0.70485714,
>        -0.01918292, -0.09233685, -0.33791352, -0.45703298, -0.19628395,
>        -0.62545753, -0.21465238, -0.06599829, -0.50689421, -0.36972436,
>        -0.06034463, -0.07949023, -0.14186969, -0.08585263, -0.63552826,
>        -0.30334159, -0.05788098, -0.63138921, -0.17612089, -0.13209308,
>        -0.37335458,  0.85096428,  0.27692274, -0.09154807, -0.49983944,
>         0.02655647,  0.05288088,  0.53555915,  0.04596104, -0.27735802])
> ```
> 
> 请从我们的代码中将这些平均参数添加（或减去）到预测的姿势参数中。它应该能够解决您的问题。

thanks i have solved it.

**Comment by liuhaorandezhanghao** [comment]
> > @penincillin 手指姿势问题很可能是由 MANO 模型的平均参数引起的。平均参数是一个 45 维向量，如下所示：
> > ```
> > right-hand:
> > array([ 0.11167872, -0.04289217,  0.41644184,  0.10881133,  0.06598568,
> >         0.75622001, -0.09639297,  0.09091566,  0.18845929, -0.11809504,
> >        -0.05094385,  0.5295845 , -0.14369841, -0.0552417 ,  0.70485714,
> >        -0.01918292,  0.09233685,  0.33791352, -0.45703298,  0.19628395,
> >         0.62545753, -0.21465238,  0.06599829,  0.50689421, -0.36972436,
> >         0.06034463,  0.07949023, -0.14186969,  0.08585263,  0.63552826,
> >        -0.30334159,  0.05788098,  0.63138921, -0.17612089,  0.13209308,
> >         0.37335458,  0.85096428, -0.27692274,  0.09154807, -0.49983944,
> >        -0.02655647, -0.05288088,  0.53555915, -0.04596104,  0.27735802])
> > 
> > left-hand:
> > array([ 0.11167872,  0.04289217, -0.41644184,  0.10881133, -0.06598568,
> >        -0.75622001, -0.09639297, -0.09091566, -0.18845929, -0.11809504,
> >         0.05094385, -0.5295845 , -0.14369841,  0.0552417 , -0.70485714,
> >        -0.01918292, -0.09233685, -0.33791352, -0.45703298, -0.19628395,
> >        -0.62545753, -0.21465238, -0.06599829, -0.50689421, -0.36972436,
> >        -0.06034463, -0.07949023, -0.14186969, -0.08585263, -0.63552826,
> >        -0.30334159, -0.05788098, -0.63138921, -0.17612089, -0.13209308,
> >        -0.37335458,  0.85096428,  0.27692274, -0.09154807, -0.49983944,
> >         0.02655647,  0.05288088,  0.53555915,  0.04596104, -0.27735802])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请从我们的代码中将这些平均参数添加（或减去）到预测的姿势参数中。它应该能够解决您的问题。
> 
> thanks i have solved it.

I have the last question, is the posture parameter mapping to the unity smplx model also strictly 72-dimensional axis angle expression? Is there an average parameter that is the same as that of the hand, because my limb prediction parameters are mapped to the smplx right elbow and there is some unreasonable. Thanks for your answer

**Comment by penincillin** [comment]
@liuhaorandezhanghao 
Not quite understand your new question. Is it the 72-dim pose parameter you mentioned the body pose parameter?

**Comment by liuhaorandezhanghao** [comment]
@penincillin yes,What I want to say is that the motion mapping of the right arm is not very accurate. Are there average parameters like fingers?
![image](https://user-images.githubusercontent.com/45560746/143427730-faa3b0b1-2be2-4d91-8b30-bfe05ea04bd1.png)

**Comment by penincillin** [comment]
@penincillin 
To my knowledge, such mean parameters do not exist for body poses, at least for the Pytorch implementation. You can debug by trying to set the parameters of the right elbow to be zero and check the results.

**Comment by linyu0219** [comment]
> > @liuhaorandezhanghao 请先回答我的问题。您如何获得第三个图像/结果，因为此可视化不是从我们的代码生成的。
> 
> The third result is obtained by passing the predicted body and posture parameters to unity's smplx model。
hi，你是怎么把他用在unity的smplx里的，是否涉及到右手坐标系到左手坐标系的转换，转换方法是什么？为什么我的像下面这样 ，lhip rhip已经就开始错误了，感觉root 反转了180° 是否还需要手动调节smplx的各关节起始方向？是否直接把结果转换的四元数设置到每个transform的rotation就行？
hi, how did you use it in unity's smplx model, does it involve the conversion of the right-handed coordinate system  to the left-handed coordinate system , and what is the conversion method? Why is mine like the following, lhip rhip has already started to be wrong,root seems like 180 ° inverse,  Do I still need to manually adjust the starting direction of each joint of smplx model? If it is work by setting evevy transform's rotation use result quaternion？
