### ISSUE TITLE
about incorporating dataset training for hand moudle

### ISSUE THREAD

**Issue by dumyy** [facebookresearch/frankmocap#17]
Hello, thank you for sharing the good work.
The hand pose datasets e.g. STB, RHD don't  provide the ground-truth annotations of angle-axis pose parameter θ，so, while training with the incorporate datasets(STB/RHD), did you set the loss weight of Lθ as zero or use other process？

**Comment by penincillin** [comment]
Yes, for dataset without pose parameters (such as STB, RHD), we only use 3D joints loss and 2D joints loss in training.

**Comment by qiufeng1994** [comment]
can't we get axis-angle from 3d joints?
