### ISSUE TITLE
Feet pose estimation

### ISSUE THREAD

**Issue by rlleshi** [facebookresearch/frankmocap#172]
The current body pose estimator performs poorly on the feet for certain use-cases like tiptoeing (I guess ankle and toe information are not enough).  

I also couldn't find fine-tuned detectors for left or right feet (similar to hands) or some good 3d feet pose estimator. Do you have any general tips on what could be done to improve the pose estimation for tiptoeing in particular?

**Comment by penincillin** [comment]
@rlleshi 
Current 3D pose estimation works including ours perform poorly on 3D feet joint estimation, mainly caused by the lack of training data.
