### ISSUE TITLE
Is there another way to download mpips?

### ISSUE THREAD

**Issue by kingaladdin** [facebookresearch/frankmocap#173]
The only link I could find had everything but mpips basically. Thanks in advance, and I hope everyone have a great day.

**Comment by penincillin** [comment]
@kingaladdin 
Would you mind provide more details about ``mpips``? Is it a third-party package or a dataset?

**Comment by kingaladdin** [comment]
Referring to this step

Goto:
http://smplify.is.tue.mpg.de/downloads
Download the file: mpips-smplify_public_v2.zip

extract the file (that is inside the zip)
\smplify_public\code\models\basicModel_neutral_lbs_10_207_0_v1.0.0.pkl

**Comment by kingaladdin** [comment]
Never mind  I found the file. For some reason I was seeing the mpips_simplify_public v2 file. Thanks for getting back with me so quick though
