### ISSUE TITLE
Issues with installing detectron2 

### ISSUE THREAD

**Issue by kingaladdin** [facebookresearch/frankmocap#176]
Any insight on how to fix this error?

After I enter "pip install -e ." 
I get some success but then I get a error code in red at the last second.
" ERROR: Command errored out with exit status 1:
command: 'C:\Users\kinga\miniconda3\envs\venv_frankmocap\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\setup.py'"'"'; file='"'"
'C:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps
cwd: C:\Users\kinga\Desktop\frankmocap-main\detectron3-windows
Complete output (41 lines):
No CUDA runtime is found, using CUDA_HOME='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v10.2'
running develop
running egg_info
creating detectron2.egg-info
writing detectron2.egg-info\PKG-INFO
writing dependency_links to detectron2.egg-info\dependency_links.txt
writing requirements to detectron2.egg-info\requires.txt
writing top-level names to detectron2.egg-info\top_level.txt
writing manifest file 'detectron2.egg-info\SOURCES.txt'
reading manifest file 'detectron2.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'detectron2.egg-info\SOURCES.txt'
running build_ext
building 'detectron2._C' extension
creating build
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\Users
creating build\temp.win-amd64-3.7\Release\Users\kinga
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\box_iou_rotated
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\cocoeval
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\nms_rotated
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\ROIAlign
creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\ROIAlignRotated
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\include -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\include\TH -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\include\THC -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\include -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\include /EHsc /TpC:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\vision.cpp /Fobuild\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\vision.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
C:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
warnings.warn(msg.format('we could not find ninja.'))
C:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
warnings.warn(f'Error checking compiler version for {compiler}: {error}')
error: command 'cl.exe' failed: No such file or directory
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "C:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
return stream.closed
ValueError: underlying buffer has been detached
----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\kinga\miniconda3\envs\venv_frankmocap\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"
'C:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\setup.py'"'"'; file='"'"
'C:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by penincillin** [comment]
@kingaladdin 
It is suggested to follow the official installation guidance of Detectron2 to install it on Windows.
