### ISSUE TITLE
OpenGL.error

### ISSUE THREAD

**Issue by Taylorminer** [facebookresearch/frankmocap#177]
How to solve the problem?
![1638754172710](https://user-images.githubusercontent.com/41726592/144774589-c44f907a-1b93-4c71-b59d-4497a42840b7.jpg)

**Comment by Taylorminer** [comment]
I try to use pytoch3d. But there is a new problem.
![3](https://user-images.githubusercontent.com/41726592/144782366-7aff76a6-dcce-417b-b748-28c7f976163c.jpg)

**Comment by penincillin** [comment]
@Taylorminer 
For pytorch-3d issue, the error is raised by not importing Pytorch3dRenderer correctly. Can you just run ```from renderer.p3d_renderer import Pytorch3dRenderer``` and see what happens?

**Comment by Taylorminer** [comment]
![4](https://user-images.githubusercontent.com/41726592/144826330-1671020f-bc65-4f38-a7b5-1a806825d984.jpg)
> @Taylorminer For pytorch-3d issue, the error is raised by not importing Pytorch3dRenderer correctly. Can you just run `from renderer.p3d_renderer import Pytorch3dRenderer` and see what happens?

**Comment by penincillin** [comment]
@Taylorminer 
It seems that the CUDA is not correctly installed or the path of CUDA is not correctly set.
