### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [facebookresearch/frankmocap#178]
from detectron2 import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by penincillin** [comment]
@liuhaorandezhanghao 
It seems that CUDA-10.1 is not either correctly installed or correctly imported. Besides, CUDA 10.1 is preferred.

**Comment by Taylorminer** [comment]
> from detectron2 import _C ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

I meet the same error. The CUDA version is 11.1. Do you solve the error?

**Comment by penincillin** [comment]
@Taylorminer @liuhaorandezhanghao 
As the error itself said, ``libcudart.so.10.1`` is missing, which means CUDA version 10.1 is required here. You can either use CUDA 10.1 or install the Pytorch, Pytorch-3D that match the CUDA version on your side.

**Comment by liuhaorandezhanghao** [comment]
> > from detectron2 import _C ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
> 
> I meet the same error. The CUDA version is 11.1. Do you solve the error?

have you solved it?
