### ISSUE TITLE
what is the order of the hand joints

### ISSUE THREAD

**Issue by sailyung** [facebookresearch/frankmocap#18]
i convert joints  (body + hands)  to bvh, but the hand pose is wrong in blender (body pose is right). 
please give me some advice. thx.

**Comment by jhugestar** [comment]
Hi @sailyung , 

We are very interested in your bvh pipeline! Could you generously share or PR yours? I believe it should be helpful for many other audiences. 

Thanks,
Han

**Comment by penincillin** [comment]
@sailyung 
```
0 : Wrist
1 : Index_00
2 : Index_01
3 : Index_02
4 : Middle_00
5 : Middle_01
6 : Middle_02
7 : Little_00
8 : Little_01
9 : Little_02
10 : Ring_00
11 : Ring_01
12 : Ring_02
13 : Thumb_00
14 : Thumb_01
15 : Thumb_02
16 : Index_03
17 : Middle_03
18 : Little_03
19 : Ring_03
20 : Thumb_03
```

**Comment by sailyung** [comment]
reference MTC c++ bvhwriter, SMPLX_NEUTRAL.pkl, and full_pose(in frankmocap)

**Comment by abhin7993** [comment]
@sailyung culd you please share the link for MTC c++ bvhwriter, I am not able to find it.

**Comment by sailyung** [comment]
> @sailyung culd you please share the link for MTC c++ bvhwriter, I am not able to find it.

https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/master/FitAdam/bvh.cpp
https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/master/FitAdam/src/BVHWriter.cpp

**Comment by stspanho** [comment]
@sailyung nice! Very interested in a more detailed flow. Do you mind sharing it?

**Comment by abhin7993** [comment]
@sailyung were you able to write BVH using the MTC c++ BVHwriter.Should I put my efforts in doing the same?
