### ISSUE TITLE
CUDA error : out of memory with 4 RTX 2080 ti. 

### ISSUE THREAD

**Issue by coreqode** [facebookresearch/frankmocap#180]
![image](https://user-images.githubusercontent.com/18486587/146321647-c04cfc06-56a6-4399-a6aa-88faeaa1907f.png)

**Comment by penincillin** [comment]
@coreqode 
How do you use 4 GPU? Our code only supports single-GPU inference.

**Comment by coreqode** [comment]
@penincillin Thanks for quick reply. Even for one GPU it was giving same error.

**Comment by penincillin** [comment]
@coreqode 
I truly haven't seen this problem before. There might be something wrong in installing the [Detectron2](https://github.com/facebookresearch/detectron2) or the [hand-detector](https://github.com/ddshan/hand_detector.d2), such as the wrong version of the CUDA. You can try to use the current environment to run the example code of Detectron2 or hand detector and see whether the same problems will accur or not.

**Comment by coreqode** [comment]
Yeah, It was issue with cuda version.

**Comment by penincillin** [comment]
@coreqode 
Sounds good. Have you solved the problem?
