### ISSUE TITLE
Does the HMR customized ?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/frankmocap#187]
Does HMR customized compares with origin?

**Comment by penincillin** [comment]
@jinfagang 
What do you mean by "customize", in terms of architecture, training data, or something else?

**Comment by jinfagang** [comment]
@penincillin Yes, just compare with original HMR open sourced version. Original HMR performance nowadays it not sota

**Comment by penincillin** [comment]
@jinfagang 
The architecture is the same as HMR. The training proxy is different. Especially, the model is trained with more data obtained from [EFT](https://github.com/facebookresearch/eft).

**Comment by jinfagang** [comment]
@penincillin Does the final result better than HMR? what's the sotaest model which same output as HMR nowadays?

**Comment by penincillin** [comment]
@jinfagang 
For SOTA performance, you may refer to [METRO](https://github.com/microsoft/MeshTransformer) or [HyberIK](https://github.com/Jeff-sjtu/HybrIK)
