### ISSUE TITLE
How to Replace SMPL/SMPL-X with any custom body rig model.

### ISSUE THREAD

**Issue by Suraj520** [facebookresearch/frankmocap#19]
What if I don’t have access to SMPL/SMPL-X models ? @penincillin, can you please discuss if I can restructre the pipeline with a custom rigged body model ? If yes, It’d be great if you can share some insights.

Thanks

**Comment by penincillin** [comment]
I think it's feasible to replace SMPL/SMPL-X with other rigged body models. You can use the predicted pose parameters (which is actually relative rotations of each joint) to animate your rigged model.

**Comment by jhugestar** [comment]
@Suraj520 As mentioned by @penincillin, the output of our network is pose parameters + shape parameters + camera parameters. You may ignore shape and camera params, and find the mapping from the pose parameters (3 dim for each angle for each joint) to your custom model. This would not be very trivial, though. The rest pose of your model should be the same as SMPL and the local axis of each joint should be also the same as yours. 

But  if this can be done, this would be an interesting application, removing the dependency to SMPL models. Please keep us updated if you made any interesting progress!

**Comment by Suraj520** [comment]
Hi @penincillin and @jhugestar, Thanks for your response. I am working towards applying the aforementioned changes to a humanoid rig. I”ll keep you posted with the progress. Thanks for the assist :) !
