### ISSUE TITLE
the output of smpl

### ISSUE THREAD

**Issue by abcliguanxi** [facebookresearch/frankmocap#190]
thks for the great work! I have three question.
1. why the smpl_output.joints is [-1,1]?what does it mean if z=1 ?
2. if the smpl_output. joints location(x y z)  is relative distance,Where is the origin of the coordinate system？
3. if i can get the distance(unit meter) between the R_Knee and R_Hip from smpl_output.joints?

Looking forward to your reply！

**Comment by penincillin** [comment]
@abcliguanxi 
1. The unit of SMPL coordinates, including both joints and vertices, is meter. Strictly speaking, the joints and verts not strictly lie in [-1, 1].
2. The raw output of the SMPL has the fixed pelvis coord, which is close but not equal to (0, 0, 0).
3. You can get distance between R_Knee and R_Hip via calculating L2 distance between these two joints.

**Comment by abcliguanxi** [comment]
thks,i will close this issus
