### ISSUE TITLE
How to get face expression?

### ISSUE THREAD

**Issue by taewhankim** [facebookresearch/frankmocap#191]
Thanks for sharing great project!

I plan to make face expression with your project, however I don't know how to modify.

Your project seems to use parts in smplx except face joints,so how do I make faces expression appear? Is it reset to joint mapping or do I have to training including face?

> https://github.com/facebookresearch/frankmocap/blob/bb05b851bc3f1e27a55fd15e9f46093e7c05fc12/bodymocap/body_mocap_api.py#L79

**Comment by penincillin** [comment]
@taewhankim 
I don't quite get your point. Is it that you have already obtained the face parameters and want to combine it with body and hands or you want to extract expression from images/videos?

**Comment by taewhankim** [comment]
@penincillin 
Hi there!
First, Sorry for confusing you. As I understand, frankmocap gives 3D human mesh without Face Expression(same as smpl not smplx).
So I want to make a model that expresses even facial expressions using your model, so what should I do? Is there any good idea?
Thanks for reply and have a great day!

**Comment by penincillin** [comment]
@taewhankim 
To include facial expressions, you can use [RingNet](https://github.com/soubhiksanyal/RingNet) or [DECA](https://github.com/YadiraF/DECA) to obtain face expressions and then combine with body and hand (through SMPL-X instead of SMPL).
