### ISSUE TITLE
Question about hand detector.

### ISSUE THREAD

**Issue by mls1999725** [facebookresearch/frankmocap#198]
Hi, I'm very interested in this excellent project. I wonder how you get a third-view hand detector? Is the faster rcnn trained on a dataset that only contains hands? I found that the hands cannot be detected in the following two pictures using the given demo and the pretrained model.
![mmexport1652838141455](https://user-images.githubusercontent.com/43207078/168940089-9e2b477f-653c-48d5-8001-9269b86921d7.jpg)
![mmexport1652838142730](https://user-images.githubusercontent.com/43207078/168940105-0a018091-4ed4-4d3f-921d-116b882c4cb2.jpg)

**Comment by penincillin** [comment]
@mls1999725 
We use the hand detector provided by [100DOH](https://fouheylab.eecs.umich.edu/~dandans/projects/100DOH/).
