### ISSUE TITLE
demo/demo_loadmocap missing

### ISSUE THREAD

**Issue by haiderasad** [facebookresearch/frankmocap#199]
hi i am trying to visualize the saved pickle files from the whole body inference i did but the command you mentioned 

`Load Saved Mocap Data (pkl file)
Run the following code to load and visualize saved mocap data files
#./mocap_output/mocap is the directory where pkl files exist
python -m  demo.demo_loadmocap --pkl_dir ./mocap_output/mocap`

but the demo_loadmocap.py file is not available kindly guide

**Comment by penincillin** [comment]
@haiderasad 
Thanks for pointing it out. The doc is kind of out-of-date. Please run ```demo.demo_visualize_prediction``` to visualize the predictions from pkl files.
