### ISSUE TITLE
How to get 2d hand joints from 3d hand joints?

### ISSUE THREAD

**Issue by dulre159** [facebookresearch/frankmocap#203]
Hi i need 2d hand joints to draw them on my image but the model is giving me 'pred_joints_img' which are still 3d joints positions.
How should i convert these 3d points to 2d points? Or should i just use the x y of these points? What is z in these points then?

Thanks for the great work

**Comment by penincillin** [comment]
@dulre159 
Sorry for the delayed reply. [pred_joints_img](https://github.com/facebookresearch/frankmocap/blob/bb05b851bc3f1e27a55fd15e9f46093e7c05fc12/handmocap/hand_mocap_api.py#L222) is the projected 2d joints into image space.
