### ISSUE TITLE
handmocap training scripts?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/frankmocap#205]
how to get the training of hands based on HMR?

**Comment by penincillin** [comment]
Thanks for your interest in our work. Sadly, we have no plan to release the training code. You can refer to [previous issues](https://github.com/facebookresearch/frankmocap/issues?q=is%3Aissue+is%3Aopen+train+) for the training.

**Comment by jinfagang** [comment]
OK then, I will create a new repo for more decent hands mocap training then.
