### ISSUE TITLE
How to get rotate vector of every joint? 

### ISSUE THREAD

**Issue by haoxurt** [facebookresearch/frankmocap#206]
Hi， Thanks for the great work！    I need the rotate vector of joint, and I only get the 61 parameters from the model_regressor.
How can I get it?

**Comment by penincillin** [comment]
[Here](https://github.com/facebookresearch/frankmocap/blob/bb05b851bc3f1e27a55fd15e9f46093e7c05fc12/handmocap/hand_mocap_api.py#L197) is the the per-joint rotation of hand.
