### ISSUE TITLE
what's the difference of  ego_centric and third_view hand detector?

### ISSUE THREAD

**Issue by haoxurt** [facebookresearch/frankmocap#209]
what's the difference of  ego_centric and third_view hand detector? Which should I choose when I test with random image?

**Comment by penincillin** [comment]
@haoxurt 
`third_view` assumes arms are visible and we will use arm information to help hand detectors (majorly use arm information to distinguish left/right hands, which are often wrong predicted by hand detectors). `ego_centric` assumes no arms visible, therefore, only rely on hand detectors' predictions.
