### ISSUE TITLE
overlay parts of the model 

### ISSUE THREAD

**Issue by mh-mahmoud** [facebookresearch/frankmocap#21]
Thanks for making your amazing code public. 

I have three questions

How can I overlay only the upper body of the 3D model?

How can I get the 2D joints of the 3D model (like the output of openPose)?

For the last question, I managed to rotate and translate the 3D model, but how can I relate the 3D mesh model coordinates to the world space?

**Comment by penincillin** [comment]
@mh-mahmoud 

1. To overlay only the upper body, you can remove the faces that not belong to upper body during rendering. 
2.  [pred_joints_img](https://github.com/facebookresearch/frankmocap/blob/37e9348e56189dfca6c4e6d139008e2be90d17b2/bodymocap/body_mocap_api.py#L112) is the predicted 2D joints in image space. It's 3 dimension, you can select the first two dimension which correspond to (x, y) coords
3. [pred_vertices_img](https://github.com/facebookresearch/frankmocap/blob/37e9348e56189dfca6c4e6d139008e2be90d17b2/bodymocap/body_mocap_api.py#L111) is the SMPL-X vertices re-scaled to the image space. If you want coordinates in the world space, then you need to know the camera extrinsic parameters, which is not covered by our project.

**Comment by mh-mahmoud** [comment]
Thank you for the speedy reply. Your comments truly helped me.

**Comment by penincillin** [comment]
@mh-mahmoud 
I will close this issue. 
Please feel free to reopen it or raise a new one if you have any other questions.
