### ISSUE TITLE
How to use "pred_body_pose" data?

### ISSUE THREAD

**Issue by weiweigt** [facebookresearch/frankmocap#211]
I receive the  "pred_body_pose" data. But  I don't konw how to change this data(Axis) to  euler angle. I want to use euler angle to control 3d module. 

[ 3.0099485   0.10035214  0.25158748 -0.8615361   0.0419311   0.38255656
  -0.81809294  0.01261169 -0.3355845   0.4508554  -0.0424528   0.02691395
   1.4825702   0.02161675 -0.21902187  1.2998743   0.12727173  0.11725652
  -0.08215837 -0.05249757 -0.0335631  -0.15522236  0.15253896 -0.12054483
  -0.13261689 -0.19696917  0.18914743  0.04614531 -0.02988306 -0.01861951
  -0.31866604  0.06958129  0.24887472 -0.22699708 -0.03164617 -0.37988728
  -0.3413255  -0.10757836  0.0340411   0.04970682 -0.06025676 -0.36410204
  -0.09720173 -0.10546245  0.07603567 -0.04374665  0.0926167   0.04063269
   0.1744866  -0.18733358 -0.8674878  -0.32053262  0.0913446   0.1883328
   0.12825379 -1.0711261   0.2762861  -0.471176    1.1712983  -0.62307394
   0.36671227  0.40799057  0.26848084  0.58183473 -0.68712586 -0.21828306
  -0.14138007 -0.10939276 -0.21847066 -0.18211165  0.10142     0.24497448]

**Comment by penincillin** [comment]
`pred_body_pose` is a 72-dim vector which can be reshaped into 24 * 3. `24` represents `24` body joints and `3` represents angle-axis for each joint. You can use 3rd party Python package such as [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.as_euler.html) to convert it into euler angle representation.

**Comment by weiweigt** [comment]
I see，thank you very much!  Then I have  another question. Are these angle-axis  local or global ？

**Comment by weiweigt** [comment]
Today, I use "scipy.spatial.transform" to change angle-axis to angle-euler. And I met some question.
        
        code: 
        
        print("-----------------pred_body_pose---------------------")
        pos = 0
        while ((pos + 3) <= (pred_output_list[0]['pred_body_pose'][0].size)):
            r = R.from_rotvec([pred_output_list[0]['pred_body_pose'][0][pos], pred_output_list[0]['pred_body_pose'][0][pos + 1], pred_output_list[0]['pred_body_pose'][0][pos + 2]])
            el = r.as_euler('xyz', degrees=True)
            print(round(el[0]), " ", round(el[1]), " ", round(el[2]))
            pos = pos + 3              

        print("-----------------pred_right_hand_pose---------------------")
        pos = 0
        while ((pos + 3) <= (pred_output_list[0]['pred_right_hand_pose'][0].size)):
            r = R.from_rotvec([pred_output_list[0]['pred_right_hand_pose'][0][pos], pred_output_list[0]['pred_right_hand_pose'][0][pos + 1], pred_output_list[0]['pred_right_hand_pose'][0][pos + 2]])
            el = r.as_euler('xyz', degrees=True)
            print(round(el[0]), " ", round(el[1]), " ", round(el[2]))
            pos = pos + 3 

        print("-----------------pred_left_hand_pose---------------------")
        pos = 0
        while ((pos + 3) <= (pred_output_list[0]['pred_left_hand_pose'][0].size)):
            r = R.from_rotvec([pred_output_list[0]['pred_left_hand_pose'][0][pos], pred_output_list[0]['pred_left_hand_pose'][0][pos + 1], pred_output_list[0]['pred_left_hand_pose'][0][pos + 2]])
            el = r.as_euler('xyz', degrees=True)
            print(round(el[0]), " ", round(el[1]), " ", round(el[2]))
            pos = pos + 3 
            
        output:        
        
        -----------------pred_body_pose---------------------
				175   -7   3
				-50   14   20
				-19   -10   -22
				18   0   0
				85   12   -6
				81   1   8
				-1   -2   -1
				-10   6   -8
				-12   -6   5
				0   -1   -1
				-15   8   14
				-16   -10   -11
				-19   3   -3
				7   -13   -20
				5   12   21
				-3   2   -4
				16   -13   -50
				16   16   54
				14   -48   1
				6   43   -6
				32   24   11
				22   -8   -19
				-9   -6   -11
				-9   6   10
				-----------------pred_right_hand_pose---------------------
				9   3   23
				-21   -6   -40
				40   -5   -1
				25   -1   -32
				-10   3   -32
				-3   -1   -16
				5   10   1
				27   -5   -18
				3   -10   3
				10   -5   -31
				21   -9   -24
				-4   -9   -22
				8   -3   4
				18   12   7
				-48   -10   -9
				-----------------pred_left_hand_pose---------------------
				6   -8   4
				-16   7   50
				24   9   -2
				19   0   26
				-8   1   42
				13   -1   13
				13   -19   11
				21   8   21
				12   8   -12
				7   1   23
				17   6   28
				8   6   12
				16   0   -7
				12   -21   -9
				-52   10   -3
				
				
				
				And I use these data on 3d module.


![org_img](https://user-images.githubusercontent.com/26109734/200540874-02f9a11c-969a-4356-ace0-8f8e9f3dab5a.png)



![body](https://user-images.githubusercontent.com/26109734/200540980-420e938e-17b1-466d-b3b2-06378141e689.png)



![right_han](https://user-images.githubusercontent.com/26109734/200541038-5ba78bc3-dd1f-45aa-86d6-a9aa25e3b391.png)


![left_hand](https://user-images.githubusercontent.com/26109734/200541152-53dec63e-5f6e-4eba-bc66-69ed771eab91.png)

**Comment by weiweigt** [comment]
Here are my problems.
One is thumb no open. 
The other is hands no put on her(module) thighs.

**Comment by DimLoong** [comment]
hey guys,Why can I see you talking about gesture recognition? Yesterday,
someone asked me about gesture recognition, but I don't know why they sent
me an email.As your current email, why can I see it?

weiweigt ***@***.***> 于2022年11月8日周二 18:44写道：

**Comment by weiweigt** [comment]
Sorry, I don't know. I guess you may be an expert in this field.
