### ISSUE TITLE
Is the axis of joint angle like below?

### ISSUE THREAD

**Issue by blueskyscorpio** [facebookresearch/frankmocap#212]
Is the axis of body joint angle depicted below, like the axis of hand joint angle?
![10](https://user-images.githubusercontent.com/43981959/199945464-67fa142d-ef9d-48b7-9926-f0a94e390275.png)

**Comment by DimLoong** [comment]
If the Y axis in this picture represents the body, then this picture is
correct

在 2022年11月4日星期五，shaohg github.com> 写道：

**Comment by blueskyscorpio** [comment]
thanks for your reply.
