### ISSUE TITLE
Can the parameters of hand be used to output mano?

### ISSUE THREAD

**Issue by Juliejulie111** [facebookresearch/frankmocap#215]
Thanks for the excellent work!!!

I have extracted *.pkl files from handmocap. Everything looked so good when I used your code to output the hand mesh. However, when I tried to output mano, I got the results like the pictures shown:
![Screenshot from 2022-11-17 15-14-15](https://user-images.githubusercontent.com/115663792/202469402-c5cbcd36-7ef6-44a8-9c99-5ba7eab6968a.png)
![Screenshot from 2022-11-17 15-14-26](https://user-images.githubusercontent.com/115663792/202469414-1bde9ecf-035b-4cd9-8203-a60d49a5d0d6.png)

The index finger always looks weird, but the other fingers seem normal.

It seems that the parameters cannot be used to output mano directly. If I want to output mano, how to change the parameters?

Thanks!!!

**Comment by penincillin** [comment]
@Juliejulie111 
Our hand-part is extracted from SMPL-X which should have the same topology as MANO. The bug may be due to the MANO or SMPL-X changed the hand topology. 
To resolve the problem, I would suggest you firstly compare the topology of our hand part and MANO.
