### ISSUE TITLE
Using multcamera for hand tracking calibration

### ISSUE THREAD

**Issue by tjddn0145** [facebookresearch/frankmocap#217]
Hi, thank you for your amazing works. 

Your work is still accurate. and can I apply multi-camera calibration to your code to make it more sophisticated?

If possible, can I know which part of the code should be changed?

**Comment by penincillin** [comment]
@tjddn0145 
Thanks for the interest in our work. However, we don't support multi-camera natively, especially when you want to increase the tracking accuracy.
