### ISSUE TITLE
Some question about the initial pose of body and hand

### ISSUE THREAD

**Issue by henrycjh** [facebookresearch/frankmocap#218]
Thanks for your great work!
I have learned that the SMPL-X use the pose parameters to get the final pose from the initial pose (T-Pose), and the pose parameters for each joints is the axis-angle format rotation relative to its parent's rotation. However, I have no detail information about the actual initial coordinate of each joints, including body and hands (especially for the hands). I have tried to search in the original paper, but still got nothing.
Here is an example that I would like to know about the initial coordinates.
![joint-coordinates](https://user-images.githubusercontent.com/73419275/208064132-adf3ae93-a586-4203-bf32-fa3040d770b8.png)
Is there any documentation about it?
Thanks for your attention!

**Comment by penincillin** [comment]
@henrycjh 
Thanks for your interest in our work. We use the default initial poses of SMPL-X. I would suggest you in checking the [Official SMPL-X Repo](https://github.com/vchoutas/smplx).
