### ISSUE TITLE
About the pose of hand

### ISSUE THREAD

**Issue by henrycjh** [facebookresearch/frankmocap#222]
I got the pose of hands from the output of the demo code. When I apply the pose to an avatar, its hands have weird pose. I guess it is related to the parameter "flat_hand_mean" of the SMPLX model. So I am wondering if the Frankmocap is trained with flat_hand_mean=False? If I would like a initial "flat hand", should I train the model from scratch?

**Comment by penincillin** [comment]
@henrycjh 
This sounds like the `flat_hand_mean` issue. You can quickly check it via setting `flat_hand_mean` to true/false.
To get initial `flat hand`, you just need to add or subtract the mean, no need to train the model from scratch.

**Comment by henrycjh** [comment]
Thanks for your quick reply! Could you please tell me how can I find **the mean** ? I did not find it in the original smplx code.

**Comment by penincillin** [comment]
@henrycjh 
I believe you can find the `mean` in SMPL-X data. You may need to delve into their code to check how the mean is applied.
