### ISSUE TITLE
How to dealing with wrong hand pose?

### ISSUE THREAD

**Issue by zzzbbs** [facebookresearch/frankmocap#223]
Thank you for sharing such a excellent project! While I reproducing the project, I faced up with the following problem:
While I infer hand pose from blurred segments in the video, It comes out that the position of hand is in a definitely wrong position. 
My project should get a hand pose with a relatively correct result. 
How to deal with this situation? 

![Screenshot 2023-02-17 10:13:56](https://user-images.githubusercontent.com/81844650/219536596-717951ac-b34a-4bcd-b60f-bc9d3dff3883.png)

**Comment by penincillin** [comment]
@zzzbbs 
It's hard to avoid such failure caused by severe motion blur. We don't have a very good solution for this. You may try to use 2D keypoints (which also tend to fail under motion blur) or use temporal information to detect/correct such failure.

**Comment by zzzbbs** [comment]
> @zzzbbs It's hard to avoid such failure caused by severe motion blur. We don't have a very good solution for this. You may try to use 2D keypoints (which also tend to fail under motion blur) or use temporal information to detect/correct such failure.

Thanks for your replying. Could you provide some suggestions on detecting such failure?

**Comment by penincillin** [comment]
@zzzbbs 
There are several ways:

1. Compare the predicted 2D joints with 2D joints detected by keypoint models.
2. Compare the difference between current predictions (3D hand pose, 2D joints, etc) with previous frames.

**Comment by zzzbbs** [comment]
> @zzzbbs There are several ways:
> 
>     1. Compare the predicted 2D joints with 2D joints detected by keypoint models.
> 
>     2. Compare the difference between current predictions (3D hand pose, 2D joints, etc) with previous frames.

Thank you! I will try the ways you have suggested.

**Comment by Dong09** [comment]
> > @zzzbbs There are several ways:
> > ```
> > 1. Compare the predicted 2D joints with 2D joints detected by keypoint models.
> > 
> > 2. Compare the difference between current predictions (3D hand pose, 2D joints, etc) with previous frames.
> > ```
> 
> Thank you! I will try the ways you have suggested.

Hello, have you done this work?
