### ISSUE TITLE
Reconstruction of the hand

### ISSUE THREAD

**Issue by Apeng-Rzp** [facebookresearch/frankmocap#224]
Can a single RGB photo be used to reconstruct an executable model of the human hand using frankmocap?

**Comment by penincillin** [comment]
@Apeng-Rzp 
What do you mean by "executable model"? 
Our project aims at reconstructing 3D hand/body from a single RGB photo.

**Comment by Apeng-Rzp** [comment]
> 

Thank you for your reply. Due to the reproduction of the paper in a virtual environment, I did not succeed in reproducing it. The "executable model" I mean files in obj or mesh format. I saw that the demo of the project were all dynamic scenes. Can I restore the obj or mesh files of a static human body or hand from an RGB image?

**Comment by penincillin** [comment]
@Apeng-Rzp 
To get obj from predictions, you can refer to [this line](https://github.com/facebookresearch/frankmocap/blob/15581a6f005b575256033c2cae184c2b76a0a65b/demo/demo_handmocap.py#L119). Especially, you can save vertices and faces in [these lines](https://github.com/facebookresearch/frankmocap/blob/15581a6f005b575256033c2cae184c2b76a0a65b/mocap_utils/demo_utils.py#L144) to get obj.
