### ISSUE TITLE
The speed of handtracking.

### ISSUE THREAD

**Issue by JunfengLiu1** [facebookresearch/frankmocap#225]
Hey,awesome work!
However,when I ran `python -m demo.demo_handmocap --input_path webcam`,the speed was slow.My gpu is RTX3060,but it only had 2-3fps.Is it normal?

**Comment by penincillin** [comment]
@JunfengLiu1 
The speed sounds a little bit slow to me. You may need to delve deep into the framework to see which part is the bottleneck. It could be I/O, detection module, prediction module, or rendering.
