### ISSUE TITLE
How can i take coordinates?

### ISSUE THREAD

**Issue by selmankilincoglu** [facebookresearch/frankmocap#23]
Thanks for this awesome repo.

I want to take x,y,z coordinates of every points.
I am using --save_pred_pkl argument and taking pkl file.
But which is the coordinates? pred_vertices_smpl? pred_vertices_img? pred_joints_img?
For example, how can i take the nose coordinates?

Thanks.

**Comment by penincillin** [comment]
``pred_vertices_smpl'' and pred_vertices_img

**Comment by penincillin** [comment]
@selmankilincoglu 
pred_vertices_smpl and pred_vertices_img are both the vertiex coordinates. 
They both have shape N x 3, where N is the total number of vertices of SMPL-X and 3 corresponds to (x, y, z) coords.
The pred_vertices_smpl is the original vertices output from SMPL-X model, the coords lies in [-1, 1].
The pred_vertices_img is the scaled version of pred_vertices_smpl, it is scaled to have the same scale as the input image.
To get nose coordinates, you need to know which vertices in SMPL-X belong to nose first. Then you can select those vertices from pred_vertices_smpl or pred_vertices_img.
