### ISSUE TITLE
Problem in hand detection module...

### ISSUE THREAD

**Issue by pratik2394** [facebookresearch/frankmocap#232]
When I try to run hand detection module or hand+ body detection module, it gives the following error message...

(Body module alone works fine.)

Command:  xvfb-run -a python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output

Loading Body Pose Estimator
Loading Third View Hand Detector
Pass 'Combine redundant instructions' is not initialized.
Verify if there is a pass dependency cycle.
Required Passes:
Segmentation fault (core dumped)

Computer background: 

I have RTX 4060, 
Cuda 10.1, 11.3, 11.8, 12.1 (passing cuda 11.3 for this environment.)
I have installed torch=1.10 and detectron2 using the following command:

python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html

While building using install_frankmocap.sh it gives a lot of deprecation warning and deprecated messages...

Any help is appreciated.

**Comment by penincillin** [comment]
@pratik2394 
Hi, the bug seems to be caused by detectron2. I would suggest you to run some example code of detectron2 after installing it.

**Comment by pratik2394** [comment]
@penincillin  Thank you for replying...

I solved the issue by changing the python version.

Below are the commands that worked for me. 

#Changes from the installation instructions:

conda create -n venv_frankmocap python=3.9

conda install cudatoolkit=11.3 
conda install cudnn=8.2.0

#In addition to the above I also installed CUDA 11.3 from the official source and provided nvcc path in the .bashrc file. 

#Torch version 1.10

#detectron2 installation: 
python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html

**Comment by penincillin** [comment]
Thanks for sharing the experience!
