### ISSUE TITLE
world coordinate

### ISSUE THREAD

**Issue by dinashi** [facebookresearch/frankmocap#25]
Is there any way to convert model output to world coordinates? especially movements along z axis are not obtained in the code. Thanks

**Comment by penincillin** [comment]
@dinashi 
Sorry, current code does not support convert the output to world coordinates. We only support to convert the coords to image coordinates with estimated camera intrinsic.

**Comment by jhugestar** [comment]
@dinashi This is in our todo list to genuinely convert our output to standard mocap outputs!

**Comment by AlbertoSabater** [comment]
Hi! How can the estimated camera intrinsic parameters be used to achieve consistent depth values on the 3D (hand) coordinates? 
As far as I know, the depth of the raw 3D coordinates is relative to the base of the index finger, not the camera or the world.

Thanks in advance
