### ISSUE TITLE
No moduel named model

### ISSUE THREAD

**Issue by abhin7993** [facebookresearch/frankmocap#26]
I am getting the following error when I try to run demo_frankmocap

Traceback (most recent call last):
  File "/home/abhinavadmin/anaconda3/envs/venv_frankmocap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/abhinavadmin/anaconda3/envs/venv_frankmocap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/abhinavadmin/frankmocap/demo/demo_frankmocap.py", line 24, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/abhinavadmin/frankmocap/handmocap/hand_bbox_detector.py", line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'

**Comment by abhin7993** [comment]
Solved the issue by installing pytorch1.4

**Comment by abhin7993** [comment]
Sorry for the previosu comment.I am still facing th same issue when using total mocap.Body mocap is working fine though.
I have checked with both pytorch1.6 and 1.4
I dont get any error while installing detectron.
Could you please suggets, how can I check if detectron is working fine or not.

**Comment by SasuraiNoHoge** [comment]
I confirmed detectron2 below:
```bash
git clone https://github.com/facebookresearch/detectron2.git
cd demo
python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input input1.jpg --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```

- Need to prepare for ``input1.jpg``

If you want to know, please check [Getting Started with Detectron2](https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md).

**Comment by abhin7993** [comment]
@SasuraiNoHoge Thanks for your help.
I have been able to solve it.Apparently the issue was with Cuda not been able to read some files.

**Comment by nhdang223** [comment]
Hello @abhin7993,

I am facing the same issue as yours, could you point out in detail how you have solved it?

Thank you so much!
