### ISSUE TITLE
Opendr broken pip

### ISSUE THREAD

**Issue by LucaswasTaken** [facebookresearch/frankmocap#29]
Hello,
Congratulations on this excellent repository with such a didactic way to democratize the 3d pose estimation. The issue that I experienced is regarding the Opendr pip installation inside the requirements. It seems like, at least for ubuntu 20.04 and python 3.7.9, the pip installation is not working. It was easily solved by installing the Opendr direct from the repository https://github.com/polmorenoc/opendr by "setup.py." However, I thought that it might be important to share.
Best regards, and thanks for the excellent work.

**Comment by penincillin** [comment]
@LucaswasTaken 
Thanks for sharing your solution ! It's really helpful !
Thanks !

**Comment by lisa676** [comment]
@LucaswasTaken Thanks for this solution. I was facing the same issue in Ubuntu 18.04. I followed your suggestion and now it is installed successfully.

**Comment by bjoernpl** [comment]
Following [this comment](https://github.com/mattloper/opendr/issues/30#issuecomment-479442146), installing ``libosmesa6-dev`` with ``sudo apt install libosmesa6-dev`` solved the problem for me with Ubuntu 18.04 and python 3.7.

**Comment by penincillin** [comment]
@bjoernpl 
Thanks for sharing your solution here !

**Comment by lisa676** [comment]
@bjoernpl  in my case it didn't work but @LucaswasTaken worked seamlessly

**Comment by yasg061** [comment]
Yeah, I use Ubuntu 20.04 and Python 3.7 and you should to upgrade to 3.8.5 version then I had some problems with OpenCV `sklearn`, `easydict` modules, but is only to look a little bit in Stackoverflow and everything is gonna be okay :+1: 

For me this commands resolve this errors:

> `pip install -U scikit-learn scipy matplotlib`

> `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --default-timeout=1000 EasyDict`

**Comment by santutu** [comment]
This worked for me
```
sudo apt install libosmesa6-dev
sudo apt-get install build-essential
sudo apt-get install libgl1-mesa-dev
sudo apt-get install libglu1-mesa-dev
sudo apt-get install freeglut3-dev
```
