### ISSUE TITLE
what do you mean by "body pose parameter in angle-axis format" ?

### ISSUE THREAD

**Issue by abhin7993** [facebookresearch/frankmocap#32]
In pkl output, I am able to see bode pose parameters [24*3].I guess these corresponds to x,y,z position of corresponding point.If yes then what do you mean by "angle-axis" format.I tried to plot them assuming x,y,z position, but that doesn't lead to a human pose.
Could you please explain a bit more about it.Excuse me if its trivial. I am not very experienced in human pose estimation.

**Comment by penincillin** [comment]
@abhin7993 
The body pose parameters [24*3] does not record the joint positions (x, y, z). It records the relative rotation of each bone. For example, rotation of upper arm relative to shoulder. 
If you want the joint positions, you can use [pred_joints_3d](https://github.com/facebookresearch/frankmocap/blob/741f9c9cc6d7b0226755fb5749ee55f7ad80457f/bodymocap/body_mocap_api.py#L85)

**Comment by abhin7993** [comment]
Thanks for the help.Will check for pred_joints_3d
