### ISSUE TITLE
How to use several datasets?

### ISSUE THREAD

**Issue by dumyy** [facebookresearch/frankmocap#35]
Hello,thanks for sharing the great peroject.
The hand model is trained with several datasets e.g. freihand, ho-3d, RHD, STB and .... Yeah, it works well. But I have some confusion about the training process. The datasets could be used in two ways.
1) The hand module is trained on one dataset, then use the trained model as the pretrained model to continue training the net module on another dataset one by one until all datasets are fed.
2) Or just mix all the dataset to one so big but diverse dataset, and use the mixed dataset to train the network.

So, could you please give me some details about the dataset training manner?  The first or the second? Or just other manner?
Thanks again!

**Comment by penincillin** [comment]
@dumyy 
We train hand module from scratch using FreiHAND and HO3D. Then we use the obtained weights to initialize and further train the model on MTC dataset, STB, RHD, FreiHAND and HO3D.

**Comment by dumyy** [comment]
Thanks for your reply. 
In fact, I wanna know the data detail about  "Ablation study on dataset."  of the paper.  In the last row of Table.3 , all the datasets " Frei HO3D MTC STB RHD " are used for training, named "full set". So, did it also follow the same rule that the hand module is trained using Freihand and HO3D, then trained using the combined datasets MTC RHD and STB?

**Comment by penincillin** [comment]
@dumyy 
Yes, model trained with "full set" is exactly the way I described.
