### ISSUE TITLE
Request for license to be unrestrictive like googles mediapipe

### ISSUE THREAD

**Issue by delebash** [facebookresearch/frankmocap#38]
There are some many project out there this being one of the best I have seen but they are all limited to academic research or non-profit. I would like to request that you could be one of the first to open up a wonderful project to the community without any restrictions. Thank you.

Google has opened up there similar projects with [mediapipe ](https://mediapipe.dev/) and tensorflow I am hoping you might follow suit.

Thanks

**Comment by jhugestar** [comment]
Hi @delebash,

Thanks for your suggestions! However, this project is based on many previous academic research outputs, codes, and datasets which are only allowed for nonprofit academic research only. Thus, this project should follow the same constraints. Sorry that we cannot provide any better answer for you.

**Comment by delebash** [comment]
I understand and thanks for the info.
