### ISSUE TITLE
question about hand joints 

### ISSUE THREAD

**Issue by lisa676** [facebookresearch/frankmocap#39]
From this repo I can get 3D body joints from here `pred_joints_3d` https://github.com/facebookresearch/frankmocap/blob/741f9c9cc6d7b0226755fb5749ee55f7ad80457f/bodymocap/body_mocap_api.py#L85 as @penincillin answered in issue #32 that "The body pose parameters [24*3] does not record the joint positions (x, y, z). It records the relative rotation of each bone. For example, rotation of upper arm relative to shoulder." 
So if we want 3D body joints then we need to use `pred_joints_3d` 

So my question is that how I can get only 3D hands joints same as 3D body joints. I can get `hand_pose_params` https://github.com/facebookresearch/frankmocap/blob/741f9c9cc6d7b0226755fb5749ee55f7ad80457f/handmocap/hand_mocap_api.py#L194 from above but where to get 3D joints only for hands?

**Comment by ahsan3803** [comment]
@lisa676 I think it is trivial to get 3D hand joints from SMPLX, check [get_smplx_output](https://github.com/facebookresearch/frankmocap/blob/b8bb7b587c0841b9292edb147729de581c66054c/handmocap/hand_modules/h3dw_model.py#L212) and [get_pred_result](https://github.com/facebookresearch/frankmocap/blob/b8bb7b587c0841b9292edb147729de581c66054c/handmocap/hand_modules/h3dw_model.py#L278) to get predicted 3D joints. Hope so it will work.

**Comment by penincillin** [comment]
@lisa676 
Under which scenario you want to obtain hand joints ? Is the hand alone scenario or hand plus body ?

**Comment by lisa676** [comment]
@penincillin Hand alone scenario
@ahsan3803 Thanks for possible solution, I did try but unable to get, could you elaborate more about it.

**Comment by ahsan3803** [comment]
@lisa676 I was able to get 21 3D joints for each hand as author stated [in this comment](https://github.com/facebookresearch/frankmocap/issues/31#issuecomment-720055889). But when I try to draw these 3D joints then I can't get right skeleton of hand, there is little problem. @penincillin can you confirm that we need to use 3D joints from [here](https://github.com/facebookresearch/frankmocap/blob/b8bb7b587c0841b9292edb147729de581c66054c/handmocap/hand_modules/h3dw_model.py#L278) or I'm going in wrong way?

**Comment by penincillin** [comment]
@lisa676 
Please check the updated code for predicted 3D hand joints.
[predicted hand joints in original SMPL space](https://github.com/facebookresearch/frankmocap/blob/88d6dce8828e609d9f576e8e2a78800bd9184069/handmocap/hand_mocap_api.py#L188)
[predicted hand joints in image space](https://github.com/facebookresearch/frankmocap/blob/88d6dce8828e609d9f576e8e2a78800bd9184069/handmocap/hand_mocap_api.py#L222)

**Comment by penincillin** [comment]
@ahsan3803 
Please refer to the comment below.

**Comment by ahsan3803** [comment]
@penincillin I already got 3D joints in same way as you did. But in drawing 3D skeleton there is something wrong, may be problem is in my drawing code. I'm trying to solve it.

**Comment by penincillin** [comment]
@ahsan3803 
How do you draw 3D joints ? In 3D space or 2D space ?
Besides, to draw skeleton, you need to know the order of joints ? Which order are you using ?

**Comment by ahsan3803** [comment]
@penincillin I'm trying to draw these joints in 3D space. I'm using [this order](https://github.com/facebookresearch/frankmocap/issues/31#issuecomment-720055889) for joints. Seems that 3D results from SMPLX is ok but there is problem in skeleton joints. Can you confirm the order of joints that this order is ok or need to change something?

**Comment by penincillin** [comment]
@ahsan3803 
The order of hand joints are different depends on whether is predicted by hand-only module and whole body module (hand plus body).
If it is predicted from hand-only module, then the order of joints should be:

**Comment by ahsan3803** [comment]
@penincillin thanks for clarification, I was following wrong order. I will use this order to draw 3D skeleton.

**Comment by lisa676** [comment]
@ahsan3803 did you draw these points successfully?

**Comment by penincillin** [comment]
@lisa676 
Would you mind share your problems here ? Maybe I can help you :)

**Comment by lisa676** [comment]
@penincillin  Thanks Rong for your kind help. I have solved my problem. This is great repository I have ever seen. Keep it up 👍

**Comment by lisa676** [comment]
@penincillin Hi dear Rong. Today I just read your new amazing work [Chasing the Tail in Monocular 3D Human Reconstruction with Prototype Memory](https://arxiv.org/abs/2012.14739), it's really wonderful idea and work. Is there any plan to share code for this new work on Github?
