### ISSUE TITLE
AssertionError: Config file 'detectors/hand_only_detector/faster_rcnn_X_101_32x8d_FPN_3x_100DOH.yaml' does not exist!

### ISSUE THREAD

**Issue by bala1144** [facebookresearch/frankmocap#4]
Hi I tried to run the method, but I am not able to run the method of following issues.

AssertionError: Config file 'detectors/hand_only_detector/faster_rcnn_X_101_32x8d_FPN_3x_100DOH.yaml' does not exist!

When I looked at the extra_data/detectors/ I could nt find the hand_only_detector folder. 

Also. when I try to run the  python demo.demo_bodymocap

AssertionError: Path ./extra_data/smpl//basicModel_neutral_lbs_10_207_0_v1.0.0.pkl does not exist!

Can you please check and help to fix this issue.

**Comment by trilokpadhi** [comment]
For the second issue that you are facing , you have to download the SMPL model from `http://smplify.is.tue.mpg.de/main/download1` and place it in `/extra_data/smpl/`.

**Comment by bala1144** [comment]
@trilokpadhi Thank you, I fixed the second issue. (I had a typo :) )

**Comment by jhugestar** [comment]
Hi @bala1144 ,

It seem like the third-party hand detector installation was not successful. 
Can you rerun the following script again?

sh scripts/install_hand_detectors.sh


The file is actually located here, which should be downloaded in our script automatically:

https://github.com/ddshan/hand_detector.d2/blob/master/faster_rcnn_X_101_32x8d_FPN_3x_100DOH.yaml

**Comment by jhugestar** [comment]
Can you try to go this github and try to directly clone?

https://github.com/ddshan/hand_detector.d2

If it works, you may try to modify the following line?

https://github.com/facebookresearch/frankmocap/blob/1c0da25994a4de61c0fec60cb053b6e60f247d0a/scripts/install_hand_detectors.sh#L18

The original line:
git clone git@github.com:ddshan/hand_detector.d2.git

Change like the following:
git clone https://github.com/ddshan/hand_detector.d2.git

**Comment by jhugestar** [comment]
I believe the issue has been resolved. Please reopen the issue if it still does not work. Thanks!
