### ISSUE TITLE
What kind of motion blur kernel do you use?

### ISSUE THREAD

**Issue by wangtss** [facebookresearch/frankmocap#41]
First, Thank you for your great work!
In your paper, your mentioned that some motion blur augmentations were applied when training hand model,
could you please tell me what kind of motion blur kernel do you use?

**Comment by penincillin** [comment]
For motion blur generation, I use the [matlab code here](https://boracchi.faculty.polimi.it/Projects/PSFGeneration.html).

**Comment by wangtss** [comment]
> For motion blur generation, I use the [matlab code here](https://boracchi.faculty.polimi.it/Projects/PSFGeneration.html).

Thanks!!!!
