### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by Q-Y-Yang** [facebookresearch/frankmocap#42]
Hello,

I used [Frankmocap demo](https://github.com/facebookresearch/frankmocap/blob/master/demo/demo_frankmocap.py) to detect 3D body and hand joints with some data, in which a person is working beside a workbench. Interestingly, a chair on background was also detected as human.
![FRank2](https://user-images.githubusercontent.com/63272352/101171540-32061b80-3640-11eb-8847-19990cd6d5a2.PNG)

What do you suggest to improve that? An idea I have for now is just cut some background of the image.

Thanks!

**Comment by penincillin** [comment]
You can add "--single_person" to avoid this.
