### ISSUE TITLE
3D AUC on STB performance

### ISSUE THREAD

**Issue by umicoo** [facebookresearch/frankmocap#48]
Hi, thanks for your amazing work.

I used your checkpoints (hand_module/pretrained_weights/pose_shape_best.pth) and follow the evaluation metrics you mentioned in the paper to test the performance on STB. But I got only 85.2016746463078 which is less than the point in Table 2. Is there something wrong with the checkpoint?

**Comment by penincillin** [comment]
@umicoo 
First, the checkpoints we released are not the checkpoints we used to evaluate on the STB dataset.
Second, for evaluating STB, we use specified joint regressor instead of the default joint regressor of SMPL-X.

**Comment by lucaskingjade** [comment]
> @umicoo
> First, the checkpoints we released are not the checkpoints we used to evaluate on the STB dataset.
> Second, for evaluating STB, we use specified joint regressor instead of the default joint regressor of SMPL-X.

Hi penincillin,
Could you release your best checkpoints and the specified joint regressor so that we can try to reproduce the results in your paper?
Thanks!

**Comment by penincillin** [comment]
@lucaskingjade @umicoo 
We are sorry that the evaluation data and code will not be available in short term. 
To reproduce the results report in paper, you can try the following:
1. Use STB and RHD dataset in training (with data augmentation applied)
2. Train a specific joint regressor for STB dataset only. Using training data of STB.
Hope this can help you.
