### ISSUE TITLE
Hi can I use multiple cameras ? or multiple recorded videos from different angle ?

### ISSUE THREAD

**Issue by samsharam** [facebookresearch/frankmocap#49]
I'd like to use multiple cameras from different angles to improve the level of animation, is it possible ? or multiple recorded videos from different angle ?

Also is there a way to export bvh or json ?

**Comment by penincillin** [comment]
@samsharam 
Our code does not support multi-view data naturally. But there is one simple strategy you can try. You can average the predictions from multiple cameras for the same identity & pose.
We will add bvh support in the future.  As for json, we have code to export the predictions in pkl format, you can transform pkl to json.
