### ISSUE TITLE
smpl directory not copied over during installation

### ISSUE THREAD

**Issue by isysjo** [facebookresearch/frankmocap#51]
Hello, I was checking the file hierarchy after following the installation steps and I noticed that everything is in order except that 
smpl
    └── basicModel_neutral_lbs_10_207_0_v1.0.0.pkl

Does not exist within the my .extra_files directory. I have downloaded the SMPLX model and have it ready to go, but I am not sure how to get around this. This installation is being done on an macOS machine. I am new to this, so please forgive me for any novice oversights I may have had. Thanks in advance!

**Comment by penincillin** [comment]
@isysjo 
Current code only be run on Linux with GPU. To make it usable on macOS, you need to manually disable the gpu related code.
Would it be feasible for you to get a Linux machine with GPU to run our code ? Otherwise, we will add CodeLab support in future and you can use that in future.

**Comment by isysjo** [comment]
@penincillin 
Thank you for your response! It is not feasible for me to get a Linux machine at the moment, so I will wait patiently for the CodeLab support :). Thanks again!
