### ISSUE TITLE
Problem with export video demo_frankmocap

### ISSUE THREAD

**Issue by jalovi** [facebookresearch/frankmocap#54]
Hi, thank for all work with project, is amazing. 
I would like to ask some problems with the solution video.

When I watch the exported video with frankmocap if the avatar only has half the body, the legs appear overlapping and interfere with playback.
Is there a way to remove the legs or find out whether or not it has legs?
![Captura de pantalla 2020-12-30 a las 11 59 50](https://user-images.githubusercontent.com/46783659/103347182-8e6d2700-4a96-11eb-8e43-f90a9008a399.png)

**Comment by penincillin** [comment]
@jalovi 
That's truly a problem of current framework. To resolve it, you can set the joint angles of lower body to zero (hips, knees and foot).
Our code currently does not have "half-body" detection mechanism or solution, we might consider add it later.
Hope this can help you and happy new year :)

**Comment by jalovi** [comment]
Thank you very much for the quick response and solution. I will write to you again as soon as I have a solution. Happy New Year!!

**Comment by jalovi** [comment]
Could @penincillin tell me in which file the angles of the lower part of the body are modified? sorry for the inconvenience

**Comment by carlosedubarreto** [comment]
Hello @jalovi I guess its the pkl file generated when you add the --save_pred_pkl when firing frankmocap

for example
python -m demo.demo_frankmocap --input_path ./sample_data/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl

they are going to be stored in: mocap_output/mocap
![image](https://user-images.githubusercontent.com/4061130/103524915-1e2b2080-4e5d-11eb-8f1f-99d9551bf020.png)

**Comment by jalovi** [comment]
> Hola @jalovi Supongo que es el archivo pkl generado cuando agregas --save_pred_pkl al disparar frankmocap
> 
> por ejemplo,
> python -m demo.demo_frankmocap --input_path ./sample_data/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl
> 
> se almacenarán en: mocap_output / mocap.
> es un archivo para cada marco que frankmocap puede procesar (a veces no puede, por lo que se omite el archivo para ese marco)
> 
> ![imagen](https://user-images.githubusercontent.com/4061130/103524915-1e2b2080-4e5d-11eb-8f1f-99d9551bf020.png)
> 
> Yo uso este código para empaquetar solo los datos "pred_body_pose" en un solo lugar, en este caso, la variable "append_data".
> Puede que esto te ayude
> 
> ```
> pkl_path='..\\Frankmocap\\mocap_output\\mocap\\'
> list_dir = os.listdir(pkl_path)
> s_list = sorted(list_dir)
> append_data = (pd.DataFrame(pd.DataFrame.from_dict(pickle.load(open(pkl_path+s_list[0],'rb'))).pred_output_list[0]['pred_body_pose']))
> 
> for i in s_list:
>     if i == s_list[0]:
>         print('0')
>         next
>     else:
>         print(i)
>         frank_data = pickle.load(open(pkl_path+i,'rb'))
>         frank = pd.DataFrame.from_dict(frank_data)
>         if 'pred_body_pose' not in frank.columns:
>             next
>         frank_pose = pd.DataFrame(frank.pred_output_list[0]['pred_body_pose'])
>         append_data = append_data.append(frank_pose)
> ```

I execute xvfb-run -a python -m demo.demo_frankmocap  --input_path./sample_data/single_totalbody.mp4 --out_dir ./mocap_output ' and I just want him to recognize the upper body so I want to override the lower body angles. 

But thank you very much for your contribution

**Comment by carlosedubarreto** [comment]
at least add --save_pred_pkl at the end

run this:

xvfb-run -a python -m demo.demo_frankmocap --input_path./sample_data/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl

and browse through the result files using pythons "pickle.load" function.
You might find the information you need.

In the code I added as an example, is the pose estimation variable, that I use to convert to FBX keyframes. But there is much mor info in the PKL file.

**Comment by jalovi** [comment]
> at least add --save_pred_pkl at the end
> 
> run this:
> 
> xvfb-run -a python -m demo.demo_frankmocap --input_path./sample_data/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl
> 
> and browse through the result files using pythons "pickle.load" function.
> You might find the information you need.
> 
> In the code I added as an example, is the pose estimation variable, that I use to convert to FBX keyframes. But there is much mor info in the PKL file.

You are right that in the pkl files there is a lot of data but I try to make the video appear only the top of the body and remove the bottom of the body. And I think that I can only do this by removing the angles from the bottom of the body and resetting them to zero.

**Comment by carlosedubarreto** [comment]
wouldnt it be easy to convert to FBX and tweak it after converting?
So you can do some experimentation..

In this issue i share how i did to make the fbx convertion
https://github.com/facebookresearch/frankmocap/issues/50

**Comment by jalovi** [comment]
> ¿No sería fácil convertir a FBX y modificarlo de la conversión?
> Para que puedas experimentar un poco ...
> 
> En este número comparto cómo hice para realizar la conversión fbx
> [# 50](https://github.com/facebookresearch/frankmocap/issues/50)

It's a good choice but I want the video to be exported directly without having to edit it later and I don't want to put together several scripts and last even longer. 
That's why I only need the top part of the body, deactivating the other part is fine. 
Thanks anyway

**Comment by jalovi** [comment]
> Could @penincillin tell me in which file the angles of the lower part of the body are modified? sorry for the inconvenience

**Comment by jalovi** [comment]
Could @penincillin tell me in which file the angles of the lower part of the body are modified? sorry for the inconvenience

**Comment by penincillin** [comment]
@jalovi 
Sorry for the delayed response.
You can first refer to the [order of joint angles](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md#joint-angle-body) here. To fix the lower body part, you can set the joint angles of L / R Hips, L / R Knees and L / R ankles (There are 1-th, 2-th, 4-th, 5-th 7-th and 8-th joints).

**Comment by jalovi** [comment]
> @jalovi
> Perdón por la demora en la respuesta.
> Primero puede consultar el [orden de los ángulos de las articulaciones](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md#joint-angle-body) aquí. Para arreglar la parte inferior del cuerpo, puede establecer los ángulos de articulación de las caderas L / R, las rodillas L / R y los tobillos L / R (hay 1-th, 2-th, 4-th, 5-th 7-th y 8ª articulaciones).

but how do I change from the 24 and only remove the joints I need? 
Thank you for all the information

**Comment by penincillin** [comment]
@jalovi 
You can just set the value of corresponding joints to be zero.

**Comment by jalovi** [comment]
After so much time I have tried to find the exact part where the angles can be changed to zero and I have not been able to find it. 
Could someone help me and tell me how to change only one of the angles to zero. For example, 4: L_Knee.
kind regard and thanks.
