### ISSUE TITLE
3D joints output

### ISSUE THREAD

**Issue by Q-Y-Yang** [facebookresearch/frankmocap#55]
Thanks for your work!
I have questions about 3D joints locations and rotation output.

Is the third column of `pred_img_joints` the depth? Because it contains both positive and negative values. If it is depth, then where is the origin of z axis (distance)? If the origin lies in the camera, then the depth should be the same sign.
For example:
pred_joints_img:[[ 390.74615     49.098785  -149.06514  ]
 [ 336.53275     54.662476   -73.1041   ]
 [ 257.58252     97.084625   -76.1069   ]
 [ 237.26962    212.33102    -78.993065 ]
 [ 275.6853     305.63647   -140.10107  ]
 [ 414.1083      95.09487    -60.660408 ]
 [ 417.5486     216.00244    -63.482674 ]
 [ 357.40317    292.06683   -127.28589  ]
 [ 318.93048    274.93042     10.864108 ]
 [ 286.71722    313.6593       8.190479 ]
 [ 232.2674     365.68256   -152.63435  ]
 [ 268.9242     440.0937      12.79833  ]
 [ 343.40744    319.95975     15.447592 ]
 [ 404.9802     392.42572   -128.94804  ]
 [ 314.9046     432.92227     27.402205 ]
 [ 372.99844     28.811356  -157.45268  ]
 [ 396.2119      23.579697  -137.64821  ]
 [ 328.26425     17.475601  -139.92213  ]
 [ 380.43423      5.5624847  -97.695274 ]
 [ 311.8253     514.0408     -12.167442 ]
 [ 332.66678    505.26297     18.350056 ]
 [ 311.78812    418.31158     54.551823 ]
 [ 255.01738    516.3665     -37.44374  ]
 [ 228.81992    500.87808    -11.421182 ]
 [ 274.59213    434.56015     45.34534  ]
 [ 268.9242     440.0937      12.79833  ]
 [ 232.2674     365.68256   -152.63435  ]
 [ 260.23444    259.62225     15.009101 ]
 [ 377.86072    269.1056      25.666203 ]
 [ 404.9802     392.42572   -128.94804  ]
 [ 314.9046     432.92227     27.402205 ]
 [ 275.6853     305.63647   -140.10107  ]
 [ 237.26962    212.33102    -78.993065 ]
 [ 257.58252     97.084625   -76.1069   ]
 [ 414.1083      95.09487    -60.660408 ]
 [ 417.5486     216.00244    -63.482674 ]
 [ 357.40317    292.06683   -127.28589  ]
 [ 341.1523      59.68271    -78.694466 ]
 [ 374.2525     -37.75685   -153.31737  ]
 [ 318.14172    266.06372     28.740244 ]
 [ 337.04575     83.39772    -66.99801  ]
 [ 328.95578    151.211       -9.214244 ]
 [ 366.79074     43.32393   -118.1924   ]
 [ 364.16168    -15.888809  -135.93591  ]
 [ 390.74615     49.098785  -149.06514  ]
 [ 396.2119      23.579697  -137.64821  ]
 [ 372.99844     28.811356  -157.45268  ]
 [ 380.43423      5.5624847  -97.695274 ]
 [ 328.26425     17.475601  -139.92213  ]]

Besides, regarding the output `pred_body_pose`, the axis-angle representation[thetax, thetay, thetaz]for each joint, is its coordinate like below?

![rotation](https://user-images.githubusercontent.com/63272352/103350085-16572f00-4a9f-11eb-99a5-d8556d5f3ffe.PNG)
Thanks a lot!

**Comment by penincillin** [comment]
@Q-Y-Yang 
1. The output of `pred_img_joints`  is the 3D coordinates of body joints, where the format is [x, y, z].  `x` and `y` is rescaled and translated to image space and `z` is rescaled accordingly. P.S. The original vertices / joints of SMPL/SMPL-X lies in [-1, 1].
2. `pred_body_pose` is angle-axis of each body joint, but the definition of angle-axis is not `[theta_x, theta_y, theta_z]`, please refer to [wikipedia](https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation) for detailed definition.  The axis should be listed below, with right-hand rule.
![Uploading image.png…]()

**Comment by Q-Y-Yang** [comment]
> @Q-Y-Yang
> 
> 1. The output of `pred_img_joints`  is the 3D coordinates of body joints, where the format is [x, y, z].  `x` and `y` is rescaled and translated to image space and `z` is rescaled accordingly. P.S. The original vertices / joints of SMPL/SMPL-X lies in [-1, 1].
> 2. `pred_body_pose` is angle-axis of each body joint, but the definition of angle-axis is not `[theta_x, theta_y, theta_z]`, please refer to [wikipedia](https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation) for detailed definition.  The axis should be listed below, with right-hand rule.
>    ![Snip20201231_6](https://user-images.githubusercontent.com/11267794/103393199-7bbd2580-4b5c-11eb-8ecf-26d55d92051a.png)

Thanks for your quick reply and happy new year! : )
To my understanding, the three elements of `pred_body_pose` for each joint are relative rotation angles around x,y,z axis to its parent joint respectively, is it right?
Besides, actually I need calculate included angles between body parts given 3D information. Can I directly use the scaled `x,y,z` to calculate included angle? Is it like 3D angles in image space?

**Comment by penincillin** [comment]
> > @Q-Y-Yang
> > 
> > 1. The output of `pred_img_joints`  is the 3D coordinates of body joints, where the format is [x, y, z].  `x` and `y` is rescaled and translated to image space and `z` is rescaled accordingly. P.S. The original vertices / joints of SMPL/SMPL-X lies in [-1, 1].
> > 2. `pred_body_pose` is angle-axis of each body joint, but the definition of angle-axis is not `[theta_x, theta_y, theta_z]`, please refer to [wikipedia](https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation) for detailed definition.  The axis should be listed below, with right-hand rule.
> >    ![Snip20201231_6](https://user-images.githubusercontent.com/11267794/103393199-7bbd2580-4b5c-11eb-8ecf-26d55d92051a.png)
> 
> Thanks for your quick reply and happy new year! : )
> To my understanding, the three elements of `pred_body_pose` for each joint are relative rotation angles around x,y,z axis to its parent joint respectively, is it right?
> Besides, actually I need calculate included angles between body parts given 3D information. Can I directly use the scaled `x,y,z` to calculate included angle? Is it like 3D angles in image space?

`pred_body_pose` is defined in angle-axis which is not defined as rotation angles around x, y, z axis (I believe this kind of rotation definition is Euler angle).

**Comment by Q-Y-Yang** [comment]
> > > @Q-Y-Yang
> > > 
> > > 1. The output of `pred_img_joints`  is the 3D coordinates of body joints, where the format is [x, y, z].  `x` and `y` is rescaled and translated to image space and `z` is rescaled accordingly. P.S. The original vertices / joints of SMPL/SMPL-X lies in [-1, 1].
> > > 2. `pred_body_pose` is angle-axis of each body joint, but the definition of angle-axis is not `[theta_x, theta_y, theta_z]`, please refer to [wikipedia](https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation) for detailed definition.  The axis should be listed below, with right-hand rule.
> > >    ![Snip20201231_6](https://user-images.githubusercontent.com/11267794/103393199-7bbd2580-4b5c-11eb-8ecf-26d55d92051a.png)
> > 
> > 
> > Thanks for your quick reply and happy new year! : )
> > To my understanding, the three elements of `pred_body_pose` for each joint are relative rotation angles around x,y,z axis to its parent joint respectively, is it right?
> > Besides, actually I need calculate included angles between body parts given 3D information. Can I directly use the scaled `x,y,z` to calculate included angle? Is it like 3D angles in image space?
> 
> `pred_body_pose` is defined in angle-axis which is not defined as rotation angles around x, y, z axis (I believe this kind of rotation definition is Euler angle).

Thanks! I know axis angle representation should be like [axis, angle] = ([x,y,z], theta), but the `pred_body_pose` is 24 * 3. Three elements for each joint, so are they [x * theta, y * theta, z * theta]? 
And joint angles of  `pred_body_pose` are based on the zero shape below, right?
![image](https://user-images.githubusercontent.com/63272352/103529530-2055a500-4e86-11eb-83a8-7ff39362d46f.png)

Sorry, I am new in pose estimation and motion capture fields, may ask some stupid questions...

**Comment by penincillin** [comment]
The angle-axis is represented as [x * theta, y * theta, z * theta] with the L2, norm of (x, y, z) is normalized to 1. 
Therefore, given a 3D rotation represented in angle-axis as (a1, a2, a3), the L2 norm of this vector is the rotation angle surrounding the axis. The axis itself is represented by the (a1, a2, a3) then. (You can also normalize them to have unit norm, but they are actually the same axis).

**Comment by Q-Y-Yang** [comment]
Thanks a lot for your help!

**Comment by Elsaam2y** [comment]
Is there a way to extract the Euler angles from the axis-angle representation?

**Comment by liuhaorandezhanghao** [comment]
Hello, I encountered an error before it was in issues, but it seems to be closed. Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/gzh/frankmocap/frankmocap-main/demo/demo_frankmocap.py", line 27, in
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/gzh/frankmocap/frankmocap-main/handmocap/hand_bbox_detector.py", line 30, in
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named'model'
The solution should be to run frankmocap/frankmocap-main/detectors/hand_object_detector/lib/setup.py
I forgot the specific order, can you tell me




On 12/6/2021 14:22，Yu ***@***.***> wrote：

Closed #55.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by penincillin** [comment]
@liuhaorandezhanghao
