### ISSUE TITLE
About hand datasets

### ISSUE THREAD

**Issue by moondabaojian** [facebookresearch/frankmocap#58]
Thank you for your excellent work！
I have a question about hand datasets, How do you use feihand and ho-3d data sets at the same time?
The freihand parameter needs to be set to flat_ hand_ mean=false, and ho-3d needs to be set to flat_ hand_ mean=true, Is there any method of parameter conversion？

**Comment by penincillin** [comment]
`def transform_hand_pose(hand_pose):
    hands_components = ry_utils.load_pkl(MANO_MODEL_PATH)['hands_components']
    hands_mean = ry_utils.load_pkl(MANO_MODEL_PATH)['hands_mean']
    rot = rotate_global_orient(hand_pose[:3])
    pose = hand_pose[3:]-hands_mean
    return rot, pose`

**Comment by piksang** [comment]
It seems that HO3D need to change wrist pose, @penincillin  and can you provide the function of 'rotate_global_orient', thank you.
