### ISSUE TITLE
Camera depth hand coordinates

### ISSUE THREAD

**Issue by AlbertoSabater** [facebookresearch/frankmocap#59]
Hi! I am using your awesome repository to extract 3D hand skeleton coordinates. So far, the estimated joints _pred_joints_img_ are pretty accurate with respect to the original image. I can see how the X/Y coordinate values refer to the image pixels, however, the Z (depth) is relative to the hand, not the camera or the world.

Is there any way to translate this depth to the camera coordinates?
Thank you!

**Comment by penincillin** [comment]
@AlbertoSabater 
Our hand / body regressor are all monocular based method, which means predicting absolute depth is infeasible. Therefore, we only predict relative Z.
Would you mind tell me why you want absolute depth ? Maybe we can find another way to resolve it.

**Comment by AlbertoSabater** [comment]
I am facing a problem of hand action recognition under variable video circumstances (such as variable camera viewpoints). Specific actions involve a movement of the hand that goes towards/away the camera. In these situations, having non-relative values of depth is mandatory to have good movement descriptors.

**Comment by penincillin** [comment]
> I am facing a problem of hand action recognition under variable video circumstances (such as variable camera viewpoints). Specific actions involve a movement of the hand that goes towards/away the camera. In these situations, having non-relative values of depth is mandatory to have good movement descriptors.

Thanks for sharing, I understand your situation now but estimating absolute depth is supported by our code for now.
We may refer to [RootNet](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE) for obtain absolute depth.
Another thing might be helpful is that the distance to the camera is related to the size of hand in image, maybe you can use this information as the descriptor.

**Comment by AlbertoSabater** [comment]
Thank you for your answer.  I will keep working on that.
