### ISSUE TITLE
ErrorChecker.glCheckError

### ISSUE THREAD

**Issue by sulei1998** [facebookresearch/frankmocap#60]
Sorry to interrupt you! But when i try to run your demo i have met some problems! 
I have followed the https://github.com/facebookresearch/frankmocap/blob/master/docs/INSTALL.md to install the All Modules.
Everything when i install seems right. When i run the demo
```sh
xvfb-run -a python -m demo.demo_frankmocap --input_path ./sample_data/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl
```
I got 
![image](https://user-images.githubusercontent.com/56378342/103546596-33945f00-4ede-11eb-81fc-673d45d87750.png)
Could you give me some advice?

**Comment by penincillin** [comment]
@sulei1998 
The problem is related to OpenGL rendering, an easy to resolve this is to use another renderer say `OpenDR` or `Pytorch3D`.
You can specify the renderer by adding `--renderer_type opendr` or `--renderer_type pytorch3d`.

**Comment by sulei1998** [comment]
Thanks for your kind help! Now i can run the demo successfully!
