### ISSUE TITLE
How to use skeleton?

### ISSUE THREAD

**Issue by mkygogo** [facebookresearch/frankmocap#61]
run demo_bodymocap with opengl_gui, in 3D viewer press "j", cannot show the seleton, 
I found in "_visualize_gui_naive" the 'skelList' is None , 
is there some demo or readme explain the structure of "skelList" ?

**Comment by penincillin** [comment]
@mkygogo 
Please refer to [joint_order](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md) for order of joint position and joint rotation.

**Comment by mkygogo** [comment]
I add some code to sent the ’pred_joints_img‘ to function '_visualize_gui_naive', then there are some points show，but it looks really weird

![b661862e05c6fc64e87ae4312bc7956](https://user-images.githubusercontent.com/34338922/104152493-b192c180-541a-11eb-8402-c28d77ead4e4.png)
![b4787fd04592a2565560a297b855583](https://user-images.githubusercontent.com/34338922/104152495-b2c3ee80-541a-11eb-834b-1c8a02d2a446.png)


![image](https://user-images.githubusercontent.com/34338922/104152217-ddfa0e00-5419-11eb-857c-8dd81f1b50cf.png)

**Comment by mkygogo** [comment]
![f468fed1c3b7fe0dff1023176ba9321](https://user-images.githubusercontent.com/34338922/104162656-01c84e80-5430-11eb-9808-89cf9a0f7954.png)
Now I got this...
![bae3a2c1600c6ecef74bcc4053138ec](https://user-images.githubusercontent.com/34338922/104162671-055bd580-5430-11eb-8846-395fdc918b78.png)
