### ISSUE TITLE
3D loss

### ISSUE THREAD

**Issue by miooooooooooo** [facebookresearch/frankmocap#64]
Thanks for you excellent work.
Can you tell me where to calculate the 3D joint loss, is the 3D joint of SMPLX output or other place. Because the define of 3D joint coordinate is different in each dataset, and how can I convert 3D joint to the unified format to calculate loss.

**Comment by penincillin** [comment]
@miooooooooooo 
Thanks for asking. The 3D joint loss is calculated between 3D joint of SMPLX output and ground truth 3D joints.
For order of joints, you need to re-order them to make sure the order is the same.
Besides, you also need to taken skeleton scale into consideration. For example, the unit of SMPLX joint is m while unit of some datasets might be mm, so you need to unify the unit before calculating the loss

**Comment by miooooooooooo** [comment]
Thank you for your reply. But I still have some questions, is the SMPLX output has same 3D space as the provided 3D annotation of HO3D or FreiHand? Because in your paper, you say  you don't use shape parameters provided by the FreiHand and HO3D(and do you use the pose parameter to calculate pose loss?), since these are defined for the MANO model. It seems that SMPLX output can't direct calculate with the 3D annotation of FreiHand and HO3D because of different 3D space.

**Comment by penincillin** [comment]
For FreiHand and HO-3D, you can use annotated pose parameters (i.e. \theta) during training.
For shape parameters, yes, MANO hand shape space and SMPL-X hand shape space are not same. Thus we didn't use them in training.

**Comment by miooooooooooo** [comment]
I got it! Thank you so much.
