### ISSUE TITLE
requirements won't install on ubuntu 20.04

### ISSUE THREAD

**Issue by blender80** [facebookresearch/frankmocap#66]
opendr installation would fail with 
    /usr/bin/ld: cannot find -lOSMesa collect2: error: ld returned 1 exit status

This is a known issue:
https://github.com/mattloper/opendr/issues/30

solved via installing 
   sudo apt-get install libosmesa6-dev

**Comment by penincillin** [comment]
@blender80 
Would you mind try pytorch-3d for rendering is using opendr is not feasible on Ubuntu 20.04

**Comment by Momilijaz96** [comment]
I found a way around this issue by building opendr from source.
