### ISSUE TITLE
Hand crop margin 0.3 or 0.03?

### ISSUE THREAD

**Issue by jonepatr** [facebookresearch/frankmocap#69]
Hi! Thanks for excellent work, really appreciate it!

Quick question, here: https://github.com/facebookresearch/frankmocap/blob/master/handmocap/hand_mocap_api.py#L68

The code uses 0.3 but the comment refer to 0.03. Should it actually be 0.03 since the comment refers to a looser crop at 0.1?

**Comment by penincillin** [comment]
@jonepatr 
It should be 0.3. Thanks for pointing out this flaw in annotations :)
