### ISSUE TITLE
How to get hand masks?

### ISSUE THREAD

**Issue by ddshan** [facebookresearch/frankmocap#71]
Hi, thanks for this great code release. It is really cool and easy to use.

I have a question about how to convert hand meshes into masks. Currently, it gets hand vertices prediction first and then does rendering. I am wondering how to get hand masks from it easily? Any suggestion would be helpful. 
Thanks.

**Comment by penincillin** [comment]
@ddshan 
Rendering is required to obtain hand masks. If the obtained hand masks are used for calculating losses, you can consider use differentiable render such as Pytorch-3d.
