### ISSUE TITLE
Visualize Question

### ISSUE THREAD

**Issue by sulei1998** [facebookresearch/frankmocap#73]
Thanks for your great work!
When i use the hand module, i want to project the output hand and arm vertices to the image. I notice that you use the `right_hand_faces_local` as the faces. I am curious how to get the faces of the hands and arms. Or could you give me some advice about project the hand and arm vertices to the image?

**Comment by penincillin** [comment]
@sulei1998 
To obtain faces belong to a specific body part (for example, arms), you can use the joints of that body part (for arms, related joints are shoulder, wrist and elbow) to filter out vertices belong to that body part. For each vertex, you can calculate its distances to all the body joints and select the joint that has the smallest distance. Then, if the selected joint belongs to the specific body part, you can assign the vertex to belong to that body part.

**Comment by sulei1998** [comment]
> @sulei1998
> To obtain faces belong to a specific body part (for example, arms), you can use the joints of that body part (for arms, related joints are shoulder, wrist and elbow) to filter out vertices belong to that body part. For each vertex, you can calculate its distances to all the body joints and select the joint that has the smallest distance. Then, if the selected joint belongs to the specific body part, you can assign the vertex to belong to that body part.

Thank you for your kind help! I will try that.
