### ISSUE TITLE
Any way to run screenless mode without using xvfb-run?

### ISSUE THREAD

**Issue by Szy-Young** [facebookresearch/frankmocap#76]
Hi, very thanks for sharing this wonderful work!
I wonder if I can run the screenless mode without using **_xvfb-run_**, since I am using a cluster and rendering work should be distributed to nodes by **_slurm_**. Running **_xvfb-run_** on distributed nodes by **_slurm_** is a bit non-trivial and cause many problems. 
I am new to 3D rendering, and could you give me some advice for running screenless mode in an alternative way?

**Comment by jhugestar** [comment]
You can still use xvfb-run in clusters, as long as opengl is installed in nodes.
If it's tricky, I would recommend to use other options such as pytorch3d, which is slower but much easier to install.

**Comment by penincillin** [comment]
@Szy-Young 
As @jhugestar says, you can use pytorch3d or opendr for screenless rendering. To do this, you can add options ```--renderer_type pytorch3d``` or ```--renderer_type opendr```

**Comment by Szy-Young** [comment]
@jhugestar @penincillin Very thanks for your answers! I've solved the problem by turning to **opendr** visualization. The effects of this project is amazing.
