### ISSUE TITLE
Estimation Performance of body part is not reported in the paper? 

### ISSUE THREAD

**Issue by OOF-dura** [facebookresearch/frankmocap#77]
Thanks for your super great work.

I just found **for the body part prediction** you only report the running time. And not error is provided for body parts prediction (like MPJPE, etc.).
Am I missing something?
Thanks!

**Comment by penincillin** [comment]
@OOF-dura 
The evaluation results of body part is not included in the arxiv version. We have evaluated body module (SMPL-X body based) on 3DPW dataset. The MPJPE and PA-MPJPE are 94.3 and 60.0, separately.
