### ISSUE TITLE
About hand joints shift

### ISSUE THREAD

**Issue by YuyanHuang** [facebookresearch/frankmocap#78]
First, thank you for your great work!
I have a question, `pred_ joints_ 3d = hand_ output['hand_ joints_ Shift ']`  is the offset from which point (`hand_start_idx`)？

**Comment by YuyanHuang** [comment]
I already know the answer. It is `left_index1` and `right_index1`. Thank you.

**Comment by YuyanHuang** [comment]
Why use index1 as the root node instead of wrist joints?

**Comment by penincillin** [comment]
Thanks for point it out.
Use index1 is just the practice we use for build hand module. I believe it make no big different to use index1 or wrist.
