### ISSUE TITLE
Host on Colab?

### ISSUE THREAD

**Issue by RocketNinja15** [facebookresearch/frankmocap#79]
Hi!

I have a very crappy pc, I don’t even have a graphics card. I was wondering if there was a way to host it on colab using ngrok and colab

**Comment by penincillin** [comment]
@RocketNinja15 
We plan to make it support colab, but we are too busy recent days in preparing ICCV submission.
Some other people make a colab version (thanks for their effort !) in this [issue](https://github.com/facebookresearch/frankmocap/issues/28), you can first refer to their solution.
