### ISSUE TITLE
Can't find extra_data in folder_hierarchy

### ISSUE THREAD

**Issue by behnamartss** [facebookresearch/frankmocap#81]
I am a little bit new to git and ubuntu as well. I have installed most of the files in your git repository, but at the end I cannot find extra_data  folder in my anaconda folder and many of its contents. how should I know where they are? please explain a little bit more about hierarchy part which is at the end of installation section so that I know it is something I should make or it is something will be created after downloading and installing packages?
Thank you so much

**Comment by penincillin** [comment]
If you have successfully run all the commands in [install_frankmocap.sh](https://github.com/facebookresearch/frankmocap/blob/master/scripts/install_frankmocap.sh). Then there should be a folder named ``extra_data`` in the project folder, instead of in the anaconda folder.
