### ISSUE TITLE
Questions about joints rotations

### ISSUE THREAD

**Issue by sautechgroup** [facebookresearch/frankmocap#86]
Hello everyone.
We are trying to use your solution for moving an human character on Unreal 4 engine.
We know that the axes of joint angle are these shown in figure:
![axis](https://user-images.githubusercontent.com/67599023/112961356-9300b480-9145-11eb-83d5-fa499f0a8b7c.png)
We would know if this orientation is the same for each bone and if each angle written in pred_body_pose is the resultant of the angle between the previous bone and the current on each axis or has a different logic.
We are approaching to body tracking right now.
In addition, if possible, can you provide me an image of the skeleton shape and points? We tried to use opengl commands, but with no result.
Thank you in advance and thank you for the amazing job.

**Comment by sautechgroup** [comment]
> For joint order, please refer to this [doc](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md)

We got angles values from pred_body_pose. Now we need to represent these on Unreal4, but in this engine the axes of each joint are oriented in relation to prev joint, but we could use world-related axes for this. But, for doing this it would be useful to know if the orientation of each joint is the one in the image ahead independently from the initial position/rotation of joint.
Thank you.

**Comment by Br4x** [comment]
@sautechgroup if you succeed it can be awesome :D

**Comment by penincillin** [comment]
The angle values obtained from ``pred_body_pose'' are 3D rotations (in angle-axis format) relative to the parent joint.
If you want the global 3D rotation or say absolute 3D rotation. You can perform the forward kinematics.

**Comment by sautechgroup** [comment]
Sorry, I'm reading just now because of other tasks. Thank you for this clarification. We'll try to map data provided with same relation. Probably our problems are also related to differences between Unreal mesh skeleton and skeleton of the model created launching your solution. We tried to use opengl_gui commands for activating skeleton view, but with no result. We would be very gratefull if you could provide an image of skeleton view in opengl_gui. Thank you a lot.

**Comment by penincillin** [comment]
@sautechgroup 
Yeah, there is some issue in opengl_gui visualization on skeleton. Since this part is not handled by me, I cannot fix it in short terms.
As for visualization on joint skeleton, thanks for your suggestion, let me take some time to do it and update it in readme.

**Comment by penincillin** [comment]
@sautechgroup 
I've updated the skeleton of body joint [here](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md#joint-angle-body).

**Comment by sautechgroup** [comment]
> @sautechgroup
> I've updated the skeleton of body joint [here](https://github.com/facebookresearch/frankmocap/blob/master/docs/joint_order.md#joint-angle-body).

Thank you very much!
