### ISSUE TITLE
array dimensions for the concatenation axis

### ISSUE THREAD

**Issue by ybjeong530** [facebookresearch/frankmocap#88]
Hi. I encountered the following ValueError while I was running the demo.demo_bodymocap.

~/Motion Capture/frankmocap-master$ python -m demo.demo_bodymocap --input_path ./sample_data/soccer.mov --out_dir ./mocap_output
Loading Body Pose Estimator
use_smplx False
WARNING: You are using a SMPL model, with only 10 shape coefficients.
--------------------------------------
Wraning: Cannot resize the gl window
Traceback (most recent call last):
  File "/home/vrcrew/anaconda3/envs/venv_frankmocap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vrcrew/anaconda3/envs/venv_frankmocap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vrcrew/Motion Capture/frankmocap-master/demo/demo_bodymocap.py", line 178, in <module>
    main()
  File "/home/vrcrew/Motion Capture/frankmocap-master/demo/demo_bodymocap.py", line 174, in main
    run_body_mocap(args, body_bbox_detector, body_mocap, visualizer)
  File "/home/vrcrew/Motion Capture/frankmocap-master/demo/demo_bodymocap.py", line 123, in run_body_mocap
    body_bbox_list = body_bbox_list)
  File "/home/vrcrew/Motion Capture/frankmocap-master/renderer/visualizer.py", line 115, in visualize
    res_img = np.concatenate((res_img, rend_img), axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2160 and the array at index 1 has size 1080

And I am not sure how I can resolve this issue. Do you have any idea how to solve this problem? 

Best,

**Comment by penincillin** [comment]
@ybjeong530 
Would you mind share me your input video or images. I can help debug on my side.

**Comment by ybjeong530** [comment]
@penincillin
Hi. I'v changed the format to mp4 and reduce the resolution and then it worked. Thanks :)

**Comment by penincillin** [comment]
@ybjeong530 
Great news ! Then I am gonna close this issue. Please feel free to reopen it or create a new one in case you encounter with other problems.

**Comment by rlleshi** [comment]
Hi @penincillin. I have a similar problem. Reducing the resolution does help but I actually need the video to have a high resolution, otherwise, certain subtle movements might be missed. 

Would you be willing to debug this if I share the video?

**Comment by rlleshi** [comment]
Just took a look and this turned out to be trivial. The max height of OpenGL rendering is set by default as `1080`. Modify [this](https://github.com/facebookresearch/frankmocap/blob/1c0f78907e82f95e183ecae20f6a70226c7c7a18/renderer/visualizer.py#L145) line to set a new max height accordingly.

**Comment by haiderasad** [comment]
> Just took a look and this turned out to be trivial. The max height of OpenGL rendering is set by default as `1080`. Modify [this](https://github.com/facebookresearch/frankmocap/blob/1c0f78907e82f95e183ecae20f6a70226c7c7a18/renderer/visualizer.py#L145) line to set a new max height accordingly.

yup this solved it thanks!
