### ISSUE TITLE
CUDA_HOME is not set

### ISSUE THREAD

**Issue by archonic** [facebookresearch/frankmocap#90]
Following install.md and having worked through a few issues, I now have almost everything working. The ego_centric view however is saying `RuntimeError: Not compiled with GPU support`. Could someone with a working setup on Ubuntu 20 and having installed Cuda with Conda tell me what their CUDA_HOME env var is set to?

**Comment by penincillin** [comment]
@archonic 
Would you mind tell me your cuda version ?

**Comment by archonic** [comment]
I followed the install.md instructions, so it should be `cudatoolkit=10.1 cudnn=7.6.0`

**Comment by penincillin** [comment]
Your problems are due to unsuccessful installing of Detectron2. So would you mind try to install Detectron2 following their official guidance ? 
Our automatic installing scripts are tested on Ubuntu-16.04 Ubuntu-18.04. I cannot guarantee it works well on Ubuntu-20.04.

**Comment by Arpitrf** [comment]
Hi, I am facing the same issue. Can you please help @penincillin ?
